[CmdletBinding()]
param([Parameter(Mandatory)][string]$PlanPath,[Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9:._-]{1,200}$')][string]$CandidateId)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$module=Join-Path $PSScriptRoot 'deployment/SecretoBoot.Deployment.psm1';$moduleHash=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([IO.File]::ReadAllBytes($module))).ToLowerInvariant();if($moduleHash-cne'c02006ecac398602d3e59542b43b11aa0a907f0be9062ffe294f7cacd510e45a'){throw 'MANUAL_CONFIRMATION_INTEGRITY_DENIED'};Import-Module $module -Force
$envelope=Get-Content $PlanPath -Raw|ConvertFrom-Json;$validation=Test-SbDeploymentEnvelope $envelope;if(-not$validation.Valid){throw $validation.Reasons[0]};$core=$validation.Core
$matches=@($envelope.ManualConfirmationCandidates|Where-Object{[string]$_.CandidateId-ceq$CandidateId});if($matches.Count-ne1){throw 'MANUAL_CANDIDATE_IDENTITY_DENIED'};$candidate=$matches[0]
if($candidate.ArbitraryPathAllowed-ne$false-or[string]$candidate.FamilyHint-notin@('Windows','Android','Linux')){throw 'MANUAL_CANDIDATE_POLICY_DENIED'}
$expected=switch([string]$candidate.FamilyHint){'Windows'{'\EFI\Microsoft\Boot\bootmgfw.efi'};'Android'{'\EFI\BOOT\BOOTX64.EFI'};'Linux'{[string]$candidate.LoaderPath}}
if([string]$candidate.LoaderPath-ine$expected-or$expected-notmatch'^\\EFI\\[A-Za-z0-9._ -]+(?:\\[A-Za-z0-9._ -]+)*\.efi$'){throw 'MANUAL_LOADER_PATH_DENIED'}
$method=switch([string]$candidate.FamilyHint){'Windows'{'WindowsEfiChainload'};'Android'{'AndroidExistingEfiChainload'};'Linux'{'LinuxEfiChainload'}};$icon=switch([string]$candidate.FamilyHint){'Windows'{'windows.png'};'Android'{'bliss.png'};'Linux'{'linux.png'}}
$entry=[pscustomobject][ordered]@{EntryId=('manual:'+$CandidateId);DisplayName=[string]$candidate.DisplayName;Family=[string]$candidate.FamilyHint;BootMethod=$method;PartitionGuid=[string]$candidate.PartitionGuid;DiskGuid=[string]$candidate.DiskGuid;LoaderPath=$expected;IconPath=('\EFI\SecretoBoot\themes\SecretoBootV9\icons\'+$icon);Evidence=[string]$candidate.Evidence;UserConfirmed=$true;BootReady=$true}
$core.BootEntries=@(@($core.BootEntries|Where-Object{[string]$_.Family-cne[string]$candidate.FamilyHint})+$entry)
if([string]$candidate.FamilyHint-ceq'Windows'){$core.TargetEspPartitionGuid=[string]$candidate.PartitionGuid;$core.TargetEspDiskGuid=[string]$candidate.DiskGuid}
$config=[Collections.Generic.List[string]]::new();foreach($line in @('# SecretoBoot V9 - generated explicit boot menu','timeout 10','default_selection "Windows"','scanfor manual','showtools reboot,shutdown','include themes/SecretoBootV9/theme.conf','')){$config.Add($line)};foreach($item in @($core.BootEntries|Sort-Object Family,DisplayName)){$name=([string]$item.DisplayName)-replace'["\r\n]','';foreach($line in @(('menuentry "{0}" {{'-f$name),('    icon {0}'-f$item.IconPath),('    volume {0}'-f$item.PartitionGuid),('    loader {0}'-f$item.LoaderPath),'}','')){$config.Add($line)}};$core.RefindConfig=$config.ToArray()-join"`r`n"
$coreJson=$core|ConvertTo-Json -Depth 16 -Compress;$digest=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($coreJson))).ToLowerInvariant();$envelope.PlanCoreJson=$coreJson;$envelope.PlanDigest=$digest;$envelope.BootEntries=@($core.BootEntries);$target=[guid]::Empty;$envelope.Deployable=([guid]::TryParse([string]$core.TargetEspPartitionGuid,[ref]$target)-and$target-ne[guid]::Empty-and@($core.BootEntries).Count-gt0);$envelope.Status=if($envelope.Deployable){'ReadyForSecurityPreflight'}else{'ManualConfirmationRequired'}
$json=$envelope|ConvertTo-Json -Depth 16 -Compress;'SBMANUAL1';'PLAN' + "`t" + [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($json));'DEPLOYABLE' + "`t" + $(if($envelope.Deployable){'1'}else{'0'})
