[CmdletBinding(SupportsShouldProcess=$false)]
param(
    [Parameter(Mandatory)][ValidateSet('Install','InstallAndTestNextBoot','UpgradeAndTestNextBoot','RepairFirmwareEntry','TestNextBoot','MakeDefault','EnableWindowsFirstCompatibility','RestoreNativeWindowsBoot','RestorePreviousDefault','Rollback','Uninstall','Recover')][string]$Action,
    [Parameter(Mandatory)][ValidateSet('INSTALL_SECRETOBOOT_EXPERIMENTAL','INSTALL_AND_TEST_SECRETOBOOT_NEXT_BOOT','UPGRADE_FINALPOLISH_AND_TEST_NEXT_BOOT','REPAIR_SECRETOBOOT_FIRMWARE_ENTRY','TEST_SECRETOBOOT_NEXT_BOOT','MAKE_SECRETOBOOT_DEFAULT','ENABLE_WINDOWS_FIRST_FIRMWARE_COMPATIBILITY','RESTORE_NATIVE_WINDOWS_BOOT','RESTORE_PREVIOUS_DEFAULT','ROLLBACK_SECRETOBOOT','UNINSTALL_SECRETOBOOT_EXPERIMENTAL','RECOVER_SECRETOBOOT_TRANSACTION')][string]$ConsentPhrase,
    [string]$PlanPath,
    [string]$ResultPath
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$revision='Windows-Desktop-V9-FinalRelease.1-WindowsFirstCompatibilityPreflightFix.1';$supportedOwnershipRevisions=@('Windows-Desktop-RealMachine-OneShot.2','Windows-Desktop-V9-FinalPolish.1','Windows-Desktop-V9-FinalPolish.2','Windows-Desktop-V9-FinalRelease.1','Windows-Desktop-V9-FinalRelease.1-PersistentDefaultFix.1','Windows-Desktop-V9-FinalRelease.1-InstalledStateFix.1','Windows-Desktop-V9-FinalRelease.1-FirmwareRepair.1','Windows-Desktop-V9-FinalRelease.1-StateConsistencyFix.1','Windows-Desktop-V9-FinalRelease.1-OwnershipStateFix.1','Windows-Desktop-V9-FinalRelease.1-FreshInstallFix.1','Windows-Desktop-V9-FinalRelease.1-SnapshotValidationFix.1','Windows-Desktop-V9-FinalRelease.1-PersistentBootOrderFix.1','Windows-Desktop-V9-FinalRelease.1-PersistentBootOrderDiagnosticFix.1','Windows-Desktop-V9-FinalRelease.1-WindowsFirstCompatibility.1','Windows-Desktop-V9-FinalRelease.1-WindowsFirstCompatibilityPreflightFix.1');$stage='Startup';$rollbackStatus='Not required';$resolverDiagnostic='Not evaluated';$resolverContext=$null;$packageRoot=$PSScriptRoot
$stateRoot=Join-Path ([Environment]::GetFolderPath('CommonApplicationData')) 'SecretoBootV9';$statePath=Join-Path $stateRoot 'deployment-state.json';$ownershipStatePath=Join-Path $stateRoot 'ownership-manifest.json';$persistentSnapshotPath=Join-Path $stateRoot 'persistent-default-snapshot.json';$mountRoot=Join-Path $stateRoot 'mounts'
$firmwareSource=Join-Path $packageRoot 'deployment/SecretoBoot.WindowsFirmware.Native.cs';$deploymentModule=Join-Path $packageRoot 'deployment/SecretoBoot.Deployment.psm1';$hybridModule=Join-Path $packageRoot 'SecretoBoot.HybridFirmwareResolver.psm1';$upgradeModule=Join-Path $packageRoot 'SecretoBoot.OwnedRuntimeUpgrade.psm1';$commandResolutionModule=Join-Path $packageRoot 'discovery/SecretoBoot.WindowsLevel1.CommandResolution.psm1';$assetsRoot=Join-Path $packageRoot 'resources/refind/0.14.2';$packageIntegrityPath=Join-Path $packageRoot 'package-integrity.json'

function Get-Hash([string]$Path){[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([IO.File]::ReadAllBytes($Path))).ToLowerInvariant()}
function Get-StateText([object]$Value){$Value|ConvertTo-Json -Depth 16}
function Write-State([object]$Value,[string]$Path){[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($Path))|Out-Null;$temp=$Path+'.tmp';[IO.File]::WriteAllText($temp,(Get-StateText $Value),[Text.UTF8Encoding]::new($false));[IO.File]::Move($temp,$Path,$true)}
function Get-SafeReason([object]$Value){$current=$Value;for($depth=0;$depth-lt6-and$null-ne$current;$depth++){$text=if($current-is[Management.Automation.ErrorRecord]){[string]$current.Exception.Message}elseif($current-is[Exception]){[string]$current.Message}else{[string]$current};if($text-match'^[A-Z0-9_]{3,120}$'){return $text};if($current-is[Management.Automation.ErrorRecord]){$current=$current.Exception}elseif($current-is[Exception]){$current=$current.InnerException}else{$current=$null}};return 'UNEXPECTED_OPERATION_FAILURE'}
function Read-NativeRedirectedText([string]$Path){
    if(-not[IO.File]::Exists($Path)){return ''}
    $bytes=[IO.File]::ReadAllBytes($Path);if($bytes.Length-eq0){return ''}
    if($bytes.Length-ge2-and$bytes[0]-eq0xFF-and$bytes[1]-eq0xFE){return [Text.Encoding]::Unicode.GetString($bytes,2,$bytes.Length-2)}
    if($bytes.Length-ge2-and$bytes[0]-eq0xFE-and$bytes[1]-eq0xFF){return [Text.Encoding]::BigEndianUnicode.GetString($bytes,2,$bytes.Length-2)}
    if($bytes.Length-ge3-and$bytes[0]-eq0xEF-and$bytes[1]-eq0xBB-and$bytes[2]-eq0xBF){return [Text.UTF8Encoding]::new($false,$false).GetString($bytes,3,$bytes.Length-3)}
    $sample=[Math]::Min($bytes.Length,4096);$oddNulls=0;$oddCount=0
    for($i=1;$i-lt$sample;$i+=2){$oddCount++;if($bytes[$i]-eq0){$oddNulls++}}
    if($oddCount-gt0-and(($oddNulls/[double]$oddCount)-ge0.60)){return [Text.Encoding]::Unicode.GetString($bytes)}
    return [Text.UTF8Encoding]::new($false,$false).GetString($bytes)
}
function Invoke-NativeBcdEdit([string[]]$Arguments){
    $exe=Join-Path $env:SystemRoot 'System32\bcdedit.exe';if(-not[IO.File]::Exists($exe)){throw 'WINDOWS_FIRMWARE_MANAGER_UNAVAILABLE'}
    if($null-eq$Arguments-or$Arguments.Count-eq0){throw 'WINDOWS_FIRMWARE_ARGUMENTS_DENIED'}
    foreach($argument in $Arguments){if([string]::IsNullOrWhiteSpace([string]$argument)-or[string]$argument-match'[\r\n\0]'){throw 'WINDOWS_FIRMWARE_ARGUMENTS_DENIED'}}
    $stdout=[IO.Path]::GetTempFileName();$stderr=[IO.Path]::GetTempFileName()
    try{
        try{$process=Start-Process -FilePath $exe -ArgumentList $Arguments -NoNewWindow -Wait -PassThru -RedirectStandardOutput $stdout -RedirectStandardError $stderr -ErrorAction Stop}catch{throw 'WINDOWS_FIRMWARE_MANAGER_START_FAILED'}
        $outputBytes=[IO.File]::ReadAllBytes($stdout);$errorBytes=[IO.File]::ReadAllBytes($stderr)
        $output=Read-NativeRedirectedText $stdout;$error=Read-NativeRedirectedText $stderr
        if($outputBytes.Length-gt1048576-or$errorBytes.Length-gt65536){throw 'WINDOWS_FIRMWARE_MANAGER_OUTPUT_CAP_EXCEEDED'}
        return [pscustomobject]@{ExitCode=[int]$process.ExitCode;Output=[string]$output;Error=[string]$error;OutputBytesBase64=[Convert]::ToBase64String($outputBytes);Command=($exe+' '+($Arguments-join' '))}
    }finally{foreach($file in @($stdout,$stderr)){try{if([IO.File]::Exists($file)){[IO.File]::Delete($file)}}catch{}}}
}
function Get-NativeWindowsBootManagerPath {
    # Radical compatibility path: use the exact direct BCDEdit invocation that
    # succeeds interactively on Windows PowerShell 5.1, then perform only exact
    # case-insensitive token checks. No regex, no line parser, no redirected IO.
    $exe=Join-Path $env:SystemRoot 'System32\bcdedit.exe'
    if(-not[IO.File]::Exists($exe)){throw 'WINDOWS_FIRMWARE_MANAGER_UNAVAILABLE'}
    try{
        $captured=@(& $exe /enum '{bootmgr}' 2>&1)
        $exitCode=[int]$LASTEXITCODE
    }catch{
        $script:resolverDiagnostic=('Command='+$exe+' /enum {bootmgr}; DirectInvocationException='+([string]$_.Exception.Message -replace'[\r\n\t]+',' '))
        throw 'WINDOWS_BOOTMGR_QUERY_FAILED'
    }
    $text=(($captured|ForEach-Object{[string]$_}) -join [Environment]::NewLine)
    $compact=($text-replace'[\r\n\t]+',' ').Trim();if($compact.Length-gt700){$compact=$compact.Substring(0,700)}
    $script:resolverDiagnostic=('Command='+$exe+' /enum {bootmgr}; ExitCode='+$exitCode+'; Output='+$compact+'; CaptureMode=DirectExactToken')
    if($exitCode-ne0){throw 'WINDOWS_BOOTMGR_QUERY_FAILED'}
    $native='\EFI\Microsoft\Boot\bootmgfw.efi'
    $compat='\EFI\SecretoBoot\refind_x64.efi'
    $normalized=$text.ToUpperInvariant()
    if($normalized.Contains($native.ToUpperInvariant())){$script:resolverDiagnostic+='; ExactPath=NativeWindows';return $native}
    if($normalized.Contains($compat.ToUpperInvariant())){$script:resolverDiagnostic+='; ExactPath=SecretoBootCompatibility';return $compat}
    throw 'WINDOWS_BOOTMGR_PATH_MISSING'
}
function Set-NativeWindowsBootManagerPath([string]$Path){
    # Write through the same direct BCDEdit process model and verify by an
    # independent fresh exact-token readback. Only the two approved EFI paths
    # are accepted. Microsoft bootmgfw.efi itself is never touched.
    $native='\EFI\Microsoft\Boot\bootmgfw.efi';$compat='\EFI\SecretoBoot\refind_x64.efi'
    if(-not([string]::Equals($Path,$native,[StringComparison]::OrdinalIgnoreCase))-and-not([string]::Equals($Path,$compat,[StringComparison]::OrdinalIgnoreCase))){throw 'WINDOWS_BOOTMGR_PATH_DENIED'}
    $exe=Join-Path $env:SystemRoot 'System32\bcdedit.exe'
    if(-not[IO.File]::Exists($exe)){throw 'WINDOWS_FIRMWARE_MANAGER_UNAVAILABLE'}
    try{
        $captured=@(& $exe /set '{bootmgr}' path $Path 2>&1)
        $exitCode=[int]$LASTEXITCODE
    }catch{
        $script:resolverDiagnostic=('Command='+$exe+' /set {bootmgr} path '+$Path+'; DirectInvocationException='+([string]$_.Exception.Message -replace'[\r\n\t]+',' '))
        throw 'WINDOWS_BOOTMGR_PATH_WRITE_FAILED'
    }
    $text=(($captured|ForEach-Object{[string]$_}) -join [Environment]::NewLine)
    $compact=($text-replace'[\r\n\t]+',' ').Trim();if($compact.Length-gt500){$compact=$compact.Substring(0,500)}
    $script:resolverDiagnostic=('Command='+$exe+' /set {bootmgr} path '+$Path+'; ExitCode='+$exitCode+'; Output='+$compact+'; CaptureMode=DirectPowerShellWrite')
    if($exitCode-ne0){throw 'WINDOWS_BOOTMGR_PATH_WRITE_DENIED'}
    $readback=Get-NativeWindowsBootManagerPath
    if(-not([string]::Equals([string]$readback,[string]$Path,[StringComparison]::OrdinalIgnoreCase))){throw 'WINDOWS_BOOTMGR_PATH_READBACK_MISMATCH'}
    return $readback
}

function Write-OperationResult([string]$Status,[string]$Stage,[string]$Reason,[string]$Message){$safeStage=if($Stage-match'^[A-Za-z0-9]+$'){$Stage}else{'Unknown'};$safeReason=Get-SafeReason $Reason;$safeMessage=([string]$Message)-replace'[\r\n\t]',' ';if($safeMessage.Length-gt240){$safeMessage=$safeMessage.Substring(0,240)};$safeDiagnostic=([string]$resolverDiagnostic)-replace'[\r\n\t]',' ';if($safeDiagnostic.Length-gt1000){$safeDiagnostic=$safeDiagnostic.Substring(0,1000)};$lines=@('SBRESULT1',("STATUS`t$Status"),("STAGE`t$safeStage"),("REASON`t$safeReason"),("MESSAGE`t$safeMessage"),("ROLLBACK`t$rollbackStatus"),("DIAGNOSTIC`t$safeDiagnostic"),("STDOUT`t"+$(if($Status-ceq'PASS'){$safeReason}else{''})),("STDERR`t"+$(if($Status-ceq'FAIL'){$safeReason}else{''})));if($ResultPath){$allowed=[IO.Path]::GetFullPath((Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'SecretoBootV9/results'))+[IO.Path]::DirectorySeparatorChar;$full=[IO.Path]::GetFullPath($ResultPath);if(-not$full.StartsWith($allowed,[StringComparison]::OrdinalIgnoreCase)-or[IO.Path]::GetExtension($full)-cne'.result'){throw 'RESULT_PATH_DENIED'};[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($full))|Out-Null;[IO.File]::WriteAllLines($full,$lines,[Text.UTF8Encoding]::new($false))}else{$lines}}
function Assert-Administrator {if(-not([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'ELEVATION_REQUIRED'}}
function Assert-PackageIntegrity {$manifest=Get-Content $packageIntegrityPath -Raw|ConvertFrom-Json;if([string]$manifest.SchemaVersion-cne'v9-end-to-end-package-integrity-1'-or[string]$manifest.Revision-cne$revision){throw 'PACKAGE_INTEGRITY_DENIED'};foreach($property in $manifest.Files.PSObject.Properties){$path=[IO.Path]::GetFullPath((Join-Path $packageRoot $property.Name));if(-not$path.StartsWith([IO.Path]::GetFullPath($packageRoot)+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)-or-not[IO.File]::Exists($path)-or(Get-Hash $path)-cne[string]$property.Value){throw 'PACKAGE_INTEGRITY_DENIED'}}}
function Import-TrustedStorage {$manifest=Join-Path $env:SystemRoot 'System32/WindowsPowerShell/v1.0/Modules/Storage/Storage.psd1';if(-not[IO.File]::Exists($manifest)){throw 'TRUSTED_STORAGE_MODULE_MISSING'};Import-Module $manifest -Force -ErrorAction Stop;foreach($name in @('Get-Partition','Get-Disk','Add-PartitionAccessPath','Remove-PartitionAccessPath')){$command=Get-Command ('Storage\'+$name) -ErrorAction Stop;if($command.CommandType-notin@('Function','Cmdlet')){throw 'TRUSTED_STORAGE_COMMAND_DENIED'}}}
function ConvertTo-ResolvedGuid([object]$Value){$parsed=[guid]::Empty;if([guid]::TryParse(([string]$Value).Trim(),[ref]$parsed)-and$parsed-ne[guid]::Empty){return $parsed.ToString('D').ToUpperInvariant()};return $null}
function Get-ResolverError([object]$ErrorRecord){if($null-eq$ErrorRecord){return 'NONE'};return ('0x'+$ErrorRecord.Exception.HResult.ToString('X8'))}
function Set-ResolverDiagnostic([guid]$Guid,[int]$Disks,[int]$Partitions,[int]$Matches,[string[]]$Backends,[string]$ErrorCode,[string]$Reason){$description=if($null-ne$resolverContext){([string]$resolverContext.FirmwareDescription)-replace'[;\r\n\t]',' '}else{'Unknown'};$script:resolverDiagnostic='Firmware entry description='+$description+'; Firmware partition GUID parsed=Yes; Firmware GPT GUID='+$Guid.ToString('D').ToUpperInvariant()+'; Storage disks enumerated='+$Disks+'; Partitions enumerated='+$Partitions+'; Matching GPT partitions='+$Matches+'; Resolver backend attempted='+($Backends-join',')+'; Win32/native error code='+$ErrorCode+'; Final stable reason='+$Reason}
function Resolve-Partition([guid]$PartitionGuid){
    if($PartitionGuid-eq[guid]::Empty){$script:resolverDiagnostic='Firmware partition GUID parsed=No; Final stable reason=INVALID_FIRMWARE_DEVICE_PATH';throw 'INVALID_FIRMWARE_DEVICE_PATH'};$wanted=$PartitionGuid.ToString('D').ToUpperInvariant();$backends=[Collections.Generic.List[string]]::new();$partitions=@();$disks=@();$storageError=$null
    try{$backends.Add('TrustedStorage.GetPartition');$partitions=@(Storage\Get-Partition -ErrorAction Stop|Select-Object -First 4097);$disks=@(Storage\Get-Disk -ErrorAction Stop|Select-Object -First 257);if($partitions.Count-gt4096-or$disks.Count-gt256){Set-ResolverDiagnostic $PartitionGuid $disks.Count $partitions.Count 0 $backends.ToArray() 'NONE' 'STORAGE_QUERY_FAILED';throw 'STORAGE_QUERY_FAILED'}}catch{$storageError=$_;$partitions=@();$disks=@()}
    $correlation=Resolve-SbHybridStorageCorrelation -FirmwarePartitionGuid $PartitionGuid -StoragePartitions $partitions -CimPartitions @();if($correlation.Reason-ceq'AMBIGUOUS'){Set-ResolverDiagnostic $PartitionGuid $disks.Count $partitions.Count $correlation.Matches $backends.ToArray() (Get-ResolverError $storageError) 'AMBIGUOUS';throw 'AMBIGUOUS'}
    $backend='TrustedStorage.GetPartition';$partition=if($correlation.Status-ceq'Resolved'){$correlation.Partition}else{$null}
    if($null-eq$partition){
        $backends.Add('TrustedCim.MSFT_Partition');$review=Resolve-SbReviewedPowerShellCommand 'windows.os.cim';if(-not$review.Available){$reason=if($null-ne$storageError-and($storageError.Exception-is[UnauthorizedAccessException]-or$storageError.Exception.Message-match'(?i)access.*denied')){'ACCESS_DENIED'}else{'STORAGE_QUERY_FAILED'};Set-ResolverDiagnostic $PartitionGuid $disks.Count $partitions.Count 0 $backends.ToArray() (Get-ResolverError $storageError) $reason;throw $reason}
        try{$cim=@(CimCmdlets\Get-CimInstance -Namespace 'ROOT/Microsoft/Windows/Storage' -ClassName 'MSFT_Partition' -Property @('Guid','GptType','DiskNumber','PartitionNumber') -OperationTimeoutSec 10 -ErrorAction Stop|Select-Object -First 4097);if($cim.Count-gt4096){throw 'STORAGE_QUERY_FAILED'}}catch{$cimError=$_;$reason=if($_.Exception-is[UnauthorizedAccessException]-or$_.Exception.Message-match'(?i)access.*denied'){'ACCESS_DENIED'}else{'STORAGE_QUERY_FAILED'};Set-ResolverDiagnostic $PartitionGuid $disks.Count $partitions.Count 0 $backends.ToArray() (Get-ResolverError $cimError) $reason;throw $reason}
        $cimCorrelation=Resolve-SbHybridStorageCorrelation -FirmwarePartitionGuid $PartitionGuid -StoragePartitions @() -CimPartitions $cim;if($cimCorrelation.Reason-ceq'NOT_FOUND'){Set-ResolverDiagnostic $PartitionGuid $disks.Count $cim.Count 0 $backends.ToArray() 'NONE' 'NOT_FOUND';throw 'NOT_FOUND'};if($cimCorrelation.Reason-ceq'AMBIGUOUS'){Set-ResolverDiagnostic $PartitionGuid $disks.Count $cim.Count $cimCorrelation.Matches $backends.ToArray() 'NONE' 'AMBIGUOUS';throw 'AMBIGUOUS'};$cimPartition=$cimCorrelation.Partition;$actionable=@($partitions|Where-Object{[uint32]$_.DiskNumber-eq[uint32]$cimPartition.DiskNumber-and[uint32]$_.PartitionNumber-eq[uint32]$cimPartition.PartitionNumber});if($actionable.Count-ne1){try{$actionable=@(Storage\Get-Partition -DiskNumber ([uint32]$cimPartition.DiskNumber) -PartitionNumber ([uint32]$cimPartition.PartitionNumber) -ErrorAction Stop)}catch{$storageError=$_}};if($actionable.Count-eq0){$reason=if($null-ne$storageError-and($storageError.Exception-is[UnauthorizedAccessException]-or$storageError.Exception.Message-match'(?i)access.*denied')){'ACCESS_DENIED'}else{'NOT_FOUND'};Set-ResolverDiagnostic $PartitionGuid $disks.Count $cim.Count 1 $backends.ToArray() (Get-ResolverError $storageError) $reason;throw $reason};if($actionable.Count-gt1){Set-ResolverDiagnostic $PartitionGuid $disks.Count $cim.Count $actionable.Count $backends.ToArray() 'NONE' 'AMBIGUOUS';throw 'AMBIGUOUS'};$partition=$actionable[0];$backend='TrustedCim.MSFT_Partition+StorageCoordinates'
    }
    $gpt=ConvertTo-ResolvedGuid $partition.GptType;if(-not$gpt){Set-ResolverDiagnostic $PartitionGuid $disks.Count $partitions.Count 1 $backends.ToArray() 'NONE' 'NOT_GPT';throw 'NOT_GPT'};$disk=@($disks|Where-Object{[uint32]$_.Number-eq[uint32]$partition.DiskNumber});if($disk.Count-ne1){try{$disk=@(Storage\Get-Disk -Number ([uint32]$partition.DiskNumber) -ErrorAction Stop)}catch{$storageError=$_}};if($disk.Count-ne1-or[uint32]$disk[0].LogicalSectorSize-lt512){Set-ResolverDiagnostic $PartitionGuid $disks.Count $partitions.Count 1 $backends.ToArray() (Get-ResolverError $storageError) 'STORAGE_QUERY_FAILED';throw 'STORAGE_QUERY_FAILED'};$volumeGuids=@($partition.AccessPaths|Where-Object{$_-match'^\\\\\?\\Volume\{[0-9A-Fa-f-]{36}\}\\$'}|Sort-Object -Unique);if($volumeGuids.Count-gt1){Set-ResolverDiagnostic $PartitionGuid $disks.Count $partitions.Count 1 $backends.ToArray() 'NONE' 'AMBIGUOUS';throw 'AMBIGUOUS'};Set-ResolverDiagnostic $PartitionGuid $disks.Count $partitions.Count 1 @($backends.ToArray()+$backend) 'NONE' 'RESOLVED';[pscustomobject]@{Partition=$partition;Disk=$disk[0];DirectRoot=if($volumeGuids.Count){$volumeGuids[0]}else{$null};PartitionGuid=$wanted;ResolverBackend=$backend}}
function Open-PartitionAccess([guid]$PartitionGuid){$resolved=Resolve-Partition $PartitionGuid;if($resolved.DirectRoot){return [pscustomobject]@{Resolved=$resolved;Root=$resolved.DirectRoot;Temporary=$false;AccessPath=$null}};[IO.Directory]::CreateDirectory($mountRoot)|Out-Null;$accessPath=Join-Path $mountRoot ([guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($accessPath)|Out-Null;try{Storage\Add-PartitionAccessPath -InputObject $resolved.Partition -AccessPath $accessPath -ErrorAction Stop|Out-Null;$check=@(Storage\Get-Partition -DiskNumber ([uint32]$resolved.Partition.DiskNumber) -PartitionNumber ([uint32]$resolved.Partition.PartitionNumber) -ErrorAction Stop);if($check.Count-ne1-or-not@($check[0].AccessPaths|Where-Object{([string]$_).TrimEnd('\')-ieq$accessPath.TrimEnd('\')}).Count){throw 'TEMPORARY_ESP_ACCESS_VERIFICATION_DENIED'};return [pscustomobject]@{Resolved=$resolved;Root=$accessPath;Temporary=$true;AccessPath=$accessPath}}catch{try{Storage\Remove-PartitionAccessPath -InputObject $resolved.Partition -AccessPath $accessPath -ErrorAction SilentlyContinue|Out-Null}catch{};try{[IO.Directory]::Delete($accessPath)}catch{};throw}}
function Close-PartitionAccess([object]$Access){if($null-eq$Access-or$Access.Temporary-ne$true){return};Storage\Remove-PartitionAccessPath -InputObject $Access.Resolved.Partition -AccessPath $Access.AccessPath -ErrorAction Stop|Out-Null;$check=@(Storage\Get-Partition -DiskNumber ([uint32]$Access.Resolved.Partition.DiskNumber) -PartitionNumber ([uint32]$Access.Resolved.Partition.PartitionNumber) -ErrorAction Stop);if($check.Count-ne1-or@($check[0].AccessPaths|Where-Object{([string]$_).TrimEnd('\')-ieq([string]$Access.AccessPath).TrimEnd('\')}).Count){throw 'TEMPORARY_ESP_ACCESS_RELEASE_DENIED'};[IO.Directory]::Delete($Access.AccessPath)}
function Open-RecoveryAccess([object]$Transaction){if([string]$Transaction.TemporaryAccessPath){$root=[IO.Path]::GetFullPath($mountRoot)+[IO.Path]::DirectorySeparatorChar;$path=[IO.Path]::GetFullPath([string]$Transaction.TemporaryAccessPath);if(-not$path.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'RECOVERY_TEMPORARY_ACCESS_PATH_DENIED'};$resolved=Resolve-Partition ([guid]$Transaction.TargetEspPartitionGuid);$active=@($resolved.Partition.AccessPaths|Where-Object{([string]$_).TrimEnd('\')-ieq$path.TrimEnd('\')});if($active.Count-eq1){return [pscustomobject]@{Resolved=$resolved;Root=$path;Temporary=$true;AccessPath=$path}};if([IO.Directory]::Exists($path)-and-not[IO.Directory]::EnumerateFileSystemEntries($path).GetEnumerator().MoveNext()){[IO.Directory]::Delete($path)}};return Open-PartitionAccess ([guid]$Transaction.TargetEspPartitionGuid)}
function Assert-SecureBootDisabled {if([SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadSecureBootEnabled()){throw 'SECURE_BOOT_ENABLED_UNSIGNED_CHAIN_DENIED'}}
function Assert-BitLockerPrepared {$manifest=Join-Path $env:SystemRoot 'System32/WindowsPowerShell/v1.0/Modules/BitLocker/BitLocker.psd1';if(-not[IO.File]::Exists($manifest)){throw 'BITLOCKER_STATE_UNAVAILABLE_DENIED'};Import-Module $manifest -Force -ErrorAction Stop;$protected=@(BitLocker\Get-BitLockerVolume|Where-Object{[string]$_.VolumeType-eq'OperatingSystem'-and[string]$_.ProtectionStatus-eq'On'});if($protected.Count){throw 'BITLOCKER_PREPARATION_REQUIRED'}}
function Test-BoundedRegularFile([string]$Root,[string]$Relative,[long]$Minimum,[long]$Maximum){if($Relative-notmatch'^[A-Za-z0-9._ -]+(?:[\\/][A-Za-z0-9._ -]+)*$'){throw 'HYBRID_PATH_POLICY_DENIED'};$rootFull=[IO.Path]::GetFullPath($Root).TrimEnd([IO.Path]::DirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar;$path=[IO.Path]::GetFullPath((Join-Path $Root $Relative));if(-not$path.StartsWith($rootFull,[StringComparison]::OrdinalIgnoreCase)){throw 'HYBRID_PATH_CONTAINMENT_DENIED'};$info=[IO.FileInfo]::new($path);if(-not$info.Exists){return $false};if(($info.Attributes-band[IO.FileAttributes]::Directory)-ne0-or($info.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0-or$info.Length-lt$Minimum-or$info.Length-gt$Maximum){throw 'HYBRID_FILE_VALIDATION_DENIED'};return $true}
function Test-PeX64Loader([string]$Root,[string]$Relative){if(-not(Test-BoundedRegularFile $Root $Relative 4096 67108864)){return $false};$path=Join-Path $Root $Relative;$stream=[IO.File]::Open($path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{$beforeLength=$stream.Length;$buffer=New-Object byte[] ([Math]::Min(65536,$beforeLength));$read=$stream.Read($buffer,0,$buffer.Length);if($read-lt64-or$buffer[0]-ne0x4d-or$buffer[1]-ne0x5a){throw 'HYBRID_PE_VALIDATION_FAILED'};$offset=[BitConverter]::ToInt32($buffer,0x3c);if($offset-lt64-or$offset+6-gt$read-or$buffer[$offset]-ne0x50-or$buffer[$offset+1]-ne0x45-or$buffer[$offset+2]-ne0-or$buffer[$offset+3]-ne0-or[BitConverter]::ToUInt16($buffer,$offset+4)-ne0x8664){throw 'HYBRID_PE_X64_VALIDATION_FAILED'};if($stream.Length-ne$beforeLength){throw 'HYBRID_FILE_MUTATION_DETECTED'};return $true}finally{$stream.Dispose()}}
function Test-BoundedTextConfig([string]$Root,[string]$Relative){if(-not(Test-BoundedRegularFile $Root $Relative 1 1048576)){return $false};$path=Join-Path $Root $Relative;$bytes=[IO.File]::ReadAllBytes($path);if($bytes.Length-eq0-or$bytes.Length-gt1048576-or0-in$bytes){throw 'HYBRID_CONFIG_VALIDATION_FAILED'};$text=[Text.Encoding]::UTF8.GetString($bytes);if([string]::IsNullOrWhiteSpace($text)){throw 'HYBRID_CONFIG_VALIDATION_FAILED'};return $true}
function Get-CurrentBootTargetSnapshot([object]$Core,[object]$TargetAccess){
    $entries=@($Core.BootEntries);if($entries.Count-lt1-or$entries.Count-gt4096){throw 'CURRENT_BOOT_TARGET_SET_DENIED'};$snapshot=[ordered]@{};$windows=0
    foreach($entry in $entries){$partition=ConvertTo-ResolvedGuid $entry.PartitionGuid;$relative=[string]$entry.LoaderPath;if(-not$partition-or$relative-notmatch'^\\EFI\\[A-Za-z0-9._ -]+(?:\\[A-Za-z0-9._ -]+)*\.efi$'-or[string]$entry.BootMethod-notin@('WindowsEfiChainload','AndroidExistingEfiChainload','LinuxEfiChainload')){throw 'CURRENT_BOOT_TARGET_IDENTITY_DENIED'};$targetPartition=ConvertTo-ResolvedGuid $TargetAccess.Resolved.PartitionGuid;$loaderAccess=$null;try{$loaderAccess=if($partition-ceq$targetPartition){$TargetAccess}else{Open-PartitionAccess ([guid]$partition)};$trimmed=$relative.TrimStart([char]'\');if(-not(Test-PeX64Loader $loaderAccess.Root $trimmed)){throw 'CURRENT_BOOT_TARGET_MISSING'};$identity=$partition+'|'+$relative.ToLowerInvariant();if($snapshot.Contains($identity)){throw 'CURRENT_BOOT_TARGET_AMBIGUOUS'};$snapshot[$identity]=Get-Hash (Join-Path $loaderAccess.Root $trimmed);if([string]$entry.Family-ceq'Windows'-and[string]$entry.BootMethod-ceq'WindowsEfiChainload'-and$relative-ieq'\EFI\Microsoft\Boot\bootmgfw.efi'){$windows++}}finally{if($null-ne$loaderAccess-and$loaderAccess-ne$TargetAccess){Close-PartitionAccess $loaderAccess}}}
    if($windows-ne1){throw 'WINDOWS_LOADER_RECOVERY_PATH_DENIED'};return [pscustomobject]$snapshot
}
function Test-BootTargetSnapshot([object]$Expected,[object]$Actual){$expectedProperties=@($Expected.PSObject.Properties);$actualProperties=@($Actual.PSObject.Properties);if($expectedProperties.Count-ne$actualProperties.Count){throw 'BOOT_TARGET_POSTWRITE_SET_CHANGED'};foreach($property in $expectedProperties){$match=@($actualProperties|Where-Object{$_.Name-ceq$property.Name});if($match.Count-ne1-or[string]$match[0].Value-cne[string]$property.Value){throw 'BOOT_TARGET_POSTWRITE_IDENTITY_CHANGED'}}}
function Get-WindowsFirmwareEvidence([object]$Core,[byte[]]$BootOrder){$windows=@($Core.BootEntries|Where-Object{[string]$_.Family-ceq'Windows'-and[string]$_.BootMethod-ceq'WindowsEfiChainload'-and[string]$_.LoaderPath-ieq'\EFI\Microsoft\Boot\bootmgfw.efi'});if($windows.Count-ne1){throw 'WINDOWS_FIRMWARE_RECOVERY_ENTRY_DENIED'};$entryMatch=[regex]::Match([string]$windows[0].EntryId,'^firmware:Boot([0-9A-Fa-f]{4})$');if(-not$entryMatch.Success){throw 'WINDOWS_FIRMWARE_RECOVERY_ENTRY_DENIED'};if($BootOrder.Length-lt2-or($BootOrder.Length%2)-ne0){throw 'FIRMWARE_ORDER_MALFORMED'};$number=[Convert]::ToUInt16($entryMatch.Groups[1].Value,16);$present=$false;for($offset=0;$offset-lt$BootOrder.Length;$offset+=2){if([BitConverter]::ToUInt16($BootOrder,$offset)-eq$number){$present=$true;break}};if(-not$present){throw 'WINDOWS_FIRMWARE_RECOVERY_ENTRY_DENIED'};return [pscustomobject]@{EntryNumber=$number;PartitionGuid=ConvertTo-ResolvedGuid $windows[0].PartitionGuid;LoaderPath=[string]$windows[0].LoaderPath}}
function Select-HybridCandidate([object[]]$Candidates,[string]$Role){if($Candidates.Count-eq0){throw ('HYBRID_'+$Role.ToUpperInvariant()+'_TARGET_NOT_FOUND')};if($Candidates.Count-eq1){return $Candidates[0]};Add-Type -AssemblyName System.Windows.Forms;$dialog=[Windows.Forms.Form]::new();$dialog.Text='Confirm SecretoBoot '+$Role+' target';$dialog.Width=820;$dialog.Height=360;$dialog.StartPosition='CenterScreen';$label=[Windows.Forms.Label]::new();$label.Text='More than one validated '+$Role+' target exists. Select one real firmware-backed candidate or cancel.';$label.AutoSize=$true;$label.Left=15;$label.Top=15;$list=[Windows.Forms.ListBox]::new();$list.Left=15;$list.Top=45;$list.Width=770;$list.Height=210;foreach($candidate in $Candidates){$null=$list.Items.Add(('{0} | disk {1}, partition {2} | {3} | {4} bytes | {5} | {6}'-f$candidate.FirmwareDescription,$candidate.DiskNumber,$candidate.PartitionNumber,$candidate.Filesystem,$candidate.SizeBytes,$candidate.PartitionGuid,$candidate.EfiPath))};$ok=[Windows.Forms.Button]::new();$ok.Text='Confirm selected target';$ok.Left=580;$ok.Top=270;$ok.Width=205;$ok.DialogResult=[Windows.Forms.DialogResult]::OK;$dialog.Controls.AddRange(@($label,$list,$ok));$dialog.AcceptButton=$ok;if($dialog.ShowDialog()-ne[Windows.Forms.DialogResult]::OK-or$list.SelectedIndex-lt0){throw 'HYBRID_MANUAL_CONFIRMATION_CANCELLED'};$selected=$Candidates[$list.SelectedIndex];$selected.UserConfirmed=$true;return $selected}
function Confirm-ResolvedFreshInstallPlan([object]$Core){Add-Type -AssemblyName System.Windows.Forms;$lines=[Collections.Generic.List[string]]::new();$lines.Add('The trusted hybrid resolver validated these exact read-only boot targets:');$lines.Add('');foreach($entry in @($Core.BootEntries|Sort-Object Family,DisplayName)){$lines.Add(([string]$entry.Family+': '+[string]$entry.PartitionGuid+' '+[string]$entry.LoaderPath))};$lines.Add('');$lines.Add('Install only EFI\SecretoBoot and create one unordered SecretoBoot firmware entry?');$answer=[Windows.Forms.MessageBox]::Show(($lines-join[Environment]::NewLine),'Confirm resolved SecretoBoot install plan',[Windows.Forms.MessageBoxButtons]::YesNo,[Windows.Forms.MessageBoxIcon]::Warning,[Windows.Forms.MessageBoxDefaultButton]::Button2);if($answer-ne[Windows.Forms.DialogResult]::Yes){throw 'FRESH_INSTALL_RESOLVED_PLAN_CONFIRMATION_DENIED'}}
function Resolve-HybridPlan([object]$Core){
    $script:stage='HybridFirmwareInventory';$firmware=@([SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadBootInventory());if($firmware.Count-eq0){throw 'FIRMWARE_INVENTORY_EMPTY'};$candidates=@(Resolve-SbHybridFirmwareCandidates -FirmwareEntries $firmware -PartitionInventory @($Core.PartitionInventory));$validated=[Collections.Generic.List[object]]::new()
    foreach($candidate in $candidates){$access=$null;$script:resolverContext=$candidate;try{$access=Open-PartitionAccess ([guid]$candidate.PartitionGuid);$relative=([string]$candidate.EfiPath).TrimStart('\');if(-not(Test-PeX64Loader $access.Root $relative)){continue};if([string]$candidate.Role-ceq'Bliss'){foreach($required in @('kernel','initrd.img')){if(-not(Test-BoundedRegularFile $access.Root $required 1 268435456)){throw 'HYBRID_BLISS_CHAIN_INCOMPLETE'}};foreach($config in @('EFI\BOOT\android.cfg','boot\grub\grub.cfg')){if(-not(Test-BoundedTextConfig $access.Root $config)){throw 'HYBRID_BLISS_CHAIN_INCOMPLETE'}}};$candidate.ValidationState='FirmwareStorageAndLoaderValidated';$validated.Add($candidate)}finally{if($null-ne$access){Close-PartitionAccess $access}}}
    $windows=Select-HybridCandidate @($validated|Where-Object{$_.Role-ceq'Windows'}) 'Windows';$bliss=Select-HybridCandidate @($validated|Where-Object{$_.Role-ceq'Bliss'}) 'Bliss';$targets=@($windows,$bliss)+@($validated|Where-Object{$_.Role-ceq'Linux'});$targets=@($targets|Group-Object{([string]$_.PartitionGuid).ToUpperInvariant()+'|'+([string]$_.EfiPath).ToLowerInvariant()}|ForEach-Object{$_.Group[0]})
    $entries=@($targets|ForEach-Object{$icon=switch([string]$_.Role){'Windows'{'windows.png'};'Bliss'{'bliss.png'};default{'linux.png'}};[pscustomobject][ordered]@{EntryId=('firmware:'+[string]$_.FirmwareIdentifier);DisplayName=[string]$_.DisplayName;Family=if($_.Role-ceq'Bliss'){'Android'}else{[string]$_.Role};BootMethod=[string]$_.BootMethod;PartitionGuid=[string]$_.PartitionGuid;DiskGuid=[string]$_.DiskGuid;LoaderPath=[string]$_.EfiPath;IconPath=('\EFI\SecretoBoot\themes\SecretoBootV9\icons\'+$icon);Evidence='Validated existing firmware entry + GPT partition + bounded EFI loader';UserConfirmed=[bool]$_.UserConfirmed;BootReady=$true}})
    $Core.TargetEspPartitionGuid=[string]$windows.PartitionGuid;$Core.TargetEspDiskGuid=[string]$windows.DiskGuid;$Core.BootEntries=$entries;$Core.RefindConfig=New-SbHybridRefindConfig $targets;$Core|Add-Member -NotePropertyName HybridResolutionCompleted -NotePropertyValue $true -Force;return $Core
}
function Read-Ownership {
    if(-not[IO.File]::Exists($ownershipStatePath)){throw 'OWNERSHIP_STATE_MISSING'}
    try{$m=Get-Content $ownershipStatePath -Raw|ConvertFrom-Json}catch{throw 'OWNERSHIP_STATE_JSON_INVALID'}
    if('SchemaVersion'-notin$m.PSObject.Properties.Name-or[string]$m.SchemaVersion-cne'v9-ownership-manifest-1'){throw 'OWNERSHIP_SCHEMA_VERSION_UNSUPPORTED'}
    foreach($name in 'OwnershipVerified','Revision','TargetEspPartitionGuid','InstalledFiles','FirmwareEntryName','FirmwareEntryNumber','FirmwareLoadOptionBase64','BootOrderChangedByMakeDefault'){if($name-notin$m.PSObject.Properties.Name){throw 'OWNERSHIP_REQUIRED_FIELD_MISSING'}}
    if($m.OwnershipVerified-ne$true){throw 'OWNERSHIP_STATE_DENIED'}
    if([string]$m.Revision-notin$supportedOwnershipRevisions){throw 'OWNERSHIP_STATE_MIGRATION_REQUIRED'}
    if($null-eq$m.InstalledFiles-or$null-eq$m.InstalledFiles.PSObject-or@($m.InstalledFiles.PSObject.Properties).Count-eq0){throw 'OWNERSHIP_FIELD_TYPE_INVALID'}
    return $m
}
function Get-InstalledFirmwareIdentity([object]$Manifest){
    if($null-eq$Manifest){throw 'OWNERSHIP_STATE_MISSING'}
    foreach($name in 'TargetEspPartitionGuid','FirmwareEntryName','FirmwareEntryNumber','FirmwareLoadOptionBase64','InstalledFiles'){if($name-notin$Manifest.PSObject.Properties.Name){throw 'OWNERSHIP_STATE_REQUIRED_FIELD_MISSING'}}
    $partition=ConvertTo-ResolvedGuid $Manifest.TargetEspPartitionGuid;if(-not$partition){throw 'OWNERSHIP_TARGET_PARTITION_IDENTITY_INVALID'}
    $number=0;try{$number=[uint16]$Manifest.FirmwareEntryNumber}catch{throw 'OWNERSHIP_FIRMWARE_ENTRY_NUMBER_INVALID'}
    $entryName=[string]$Manifest.FirmwareEntryName;if($entryName-cne('Boot'+$number.ToString('X4'))){throw 'OWNERSHIP_FIRMWARE_ENTRY_NUMBER_MISMATCH'}
    try{$loadOption=[Convert]::FromBase64String([string]$Manifest.FirmwareLoadOptionBase64)}catch{throw 'OWNERSHIP_FIRMWARE_LOAD_OPTION_INVALID'}
    if($loadOption.Length-eq0){throw 'OWNERSHIP_FIRMWARE_LOAD_OPTION_INVALID'}
    return [pscustomobject]@{PartitionGuid=[guid]$partition;EntryNumber=$number;EntryName=$entryName;LoadOption=[byte[]]$loadOption}
}
function Get-InstalledIdentityDigest([object]$Manifest,[object]$Identity){$refind=[string]$Manifest.InstalledFiles.'refind_x64.efi';if($refind-notmatch'^[0-9a-f]{64}$'){throw 'OWNED_LOADER_HASH_MISMATCH'};$canonical=([string]$Identity.EntryName).ToUpperInvariant()+'|'+([string]$Identity.PartitionGuid).ToUpperInvariant()+'|\EFI\SecretoBoot\refind_x64.efi|'+$refind+'|'+[string]$Manifest.Revision;return [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($canonical))).ToLowerInvariant()}
function Get-CanonicalInstalledState([object]$Manifest,[object]$Identity,[object]$Access,[string]$OwnedRoot,[object]$Core,[bool]$AllowMissing){
    $script:stage='CanonicalOwnershipValidation';Test-OwnedFiles $Manifest $OwnedRoot;Test-EfiOwnershipManifest $Manifest $OwnedRoot
    $firmwareStatus='Verified';$firmware=$null;$script:stage='CanonicalFirmwareInventory';try{$firmware=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::VerifyInstalledOwnedEntry([uint16]$Identity.EntryNumber,[string]$Identity.EntryName,[byte[]]$Identity.LoadOption,[guid]$Identity.PartitionGuid)}catch{$reason=Get-SafeReason $_;if($AllowMissing-and$reason-ceq'OWNED_FIRMWARE_ENTRY_MISSING'){$firmwareStatus='Missing'}else{throw $reason}}
    $script:stage='CanonicalBootStateRead';$bootOrder=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootOrder');$bootNext=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootNext')
    $targets=$null;$windows=$null;if($null-ne$Core-and$firmwareStatus-ceq'Verified'){$script:stage='CanonicalBootTargetVerification';$targets=Get-CurrentBootTargetSnapshot $Core $Access;$script:stage='CanonicalWindowsRecoveryVerification';$windows=Get-WindowsFirmwareEvidence $Core $bootOrder}
    return [pscustomobject][ordered]@{Manifest=$Manifest;Identity=$Identity;FirmwareStatus=$firmwareStatus;FirmwareEntry=$firmware;BootOrder=[byte[]]$bootOrder;BootNext=[byte[]]$bootNext;BootTargets=$targets;WindowsRecovery=$windows;InstalledIdentityDigest=Get-InstalledIdentityDigest $Manifest $Identity;ThemeVerified=('ThemeRevision'-in$Manifest.PSObject.Properties.Name-and[string]$Manifest.ThemeRevision-ceq'FinalRelease.1'-and'ThemeDeployment'-in$Manifest.PSObject.Properties.Name-and[string]$Manifest.ThemeDeployment-ceq'MATCH');StateFreshness='Current'}
}
function ConvertTo-SnapshotGuid([object]$Value){$parsed=[guid]::Empty;if(-not[guid]::TryParse([string]$Value,[ref]$parsed)-or$parsed-eq[guid]::Empty){throw 'SNAPSHOT_FIELD_TYPE_INVALID'};$parsed.ToString('D').ToUpperInvariant()}
function ConvertTo-SnapshotEfiPath([object]$Value){$path=([string]$Value).Replace('/','\');if(-not$path.StartsWith('\')){$path='\'+$path};if($path-notmatch'^\\EFI\\[A-Za-z0-9._ -]+(?:\\[A-Za-z0-9._ -]+)*\.efi$'){throw 'SNAPSHOT_FIELD_TYPE_INVALID'};$path.ToLowerInvariant()}
function ConvertTo-SnapshotBootName([object]$Value){$number=0;if(-not[int]::TryParse([string]$Value,[ref]$number)-or$number-lt0-or$number-gt65535){throw 'SNAPSHOT_FIELD_TYPE_INVALID'};'Boot'+$number.ToString('X4')}
function Test-PersistentDefaultSnapshotReadback([object]$Expected,[object]$Actual){
    if([string]$Actual.SchemaVersion-cne'v9-persistent-default-snapshot-1'){throw 'SNAPSHOT_SCHEMA_INVALID'}
    try{$actualOrder=[Convert]::FromBase64String([string]$Actual.OriginalBootOrderBase64)}catch{throw 'SNAPSHOT_BOOTORDER_INVALID'};if([Convert]::ToBase64String($actualOrder)-cne[string]$Expected.OriginalBootOrderBase64){throw 'SNAPSHOT_BOOTORDER_INVALID'}
    if([int]$Actual.SecretoBootEntryNumber-ne[int]$Expected.SecretoBootEntryNumber-or[string]$Actual.SecretoBootEntryName-cne(ConvertTo-SnapshotBootName $Expected.SecretoBootEntryNumber)-or(ConvertTo-SnapshotGuid $Actual.SecretoBootPartitionGuid)-cne[string]$Expected.SecretoBootPartitionGuid-or(ConvertTo-SnapshotEfiPath $Actual.SecretoBootLoaderPath)-cne[string]$Expected.SecretoBootLoaderPath){throw 'SNAPSHOT_OWNED_ENTRY_INVALID'}
    if([int]$Actual.WindowsEntryNumber-ne[int]$Expected.WindowsEntryNumber-or(ConvertTo-SnapshotGuid $Actual.WindowsPartitionGuid)-cne[string]$Expected.WindowsPartitionGuid-or(ConvertTo-SnapshotEfiPath $Actual.WindowsLoaderPath)-cne[string]$Expected.WindowsLoaderPath){throw 'SNAPSHOT_WINDOWS_RECOVERY_INVALID'}
    if([string]$Actual.InstalledIdentityDigest-cne[string]$Expected.InstalledIdentityDigest){throw 'SNAPSHOT_IDENTITY_DIGEST_MISMATCH'}
    if([string]$Actual.OwnershipStateSha256-cne[string]$Expected.OwnershipStateSha256-or[string]$Actual.OwnershipRevision-cne[string]$Expected.OwnershipRevision){throw 'SNAPSHOT_OWNERSHIP_HASH_MISMATCH'}
    if([bool]$Actual.PreviousPersistentDefault-ne[bool]$Expected.PreviousPersistentDefault){throw 'SNAPSHOT_READBACK_NORMALIZATION_MISMATCH'}
    return $true
}
function New-PersistentDefaultSnapshot([object]$Canonical){
    $script:stage='PersistentDefaultBootOrderCapture';if($Canonical.BootOrder.Length-lt2-or($Canonical.BootOrder.Length%2)-ne0){throw 'BOOT_ORDER_CAPTURE_FAILED'}
    $script:stage='PersistentDefaultOwnedEntryCapture';if($Canonical.FirmwareStatus-cne'Verified'-or$null-eq$Canonical.FirmwareEntry){throw 'OWNED_ENTRY_CAPTURE_FAILED'}
    $script:stage='PersistentDefaultWindowsRecoveryCapture';if($null-eq$Canonical.WindowsRecovery){throw 'WINDOWS_RECOVERY_CAPTURE_FAILED'}
    $script:stage='PersistentDefaultOwnershipStateLoad';if(-not[IO.File]::Exists($ownershipStatePath)){throw 'OWNERSHIP_STATE_INVALID'};$ownershipHash=Get-Hash $ownershipStatePath
    $snapshot=[pscustomobject][ordered]@{SchemaVersion='v9-persistent-default-snapshot-1';Revision=$revision;CapturedUtc=[DateTime]::UtcNow.ToString('o');OriginalBootOrderBase64=[Convert]::ToBase64String([byte[]]$Canonical.BootOrder);SecretoBootEntryName=ConvertTo-SnapshotBootName $Canonical.Identity.EntryNumber;SecretoBootEntryNumber=[int]$Canonical.Identity.EntryNumber;SecretoBootPartitionGuid=ConvertTo-SnapshotGuid $Canonical.Identity.PartitionGuid;SecretoBootLoaderPath=ConvertTo-SnapshotEfiPath '\EFI\SecretoBoot\refind_x64.efi';WindowsEntryNumber=[int]$Canonical.WindowsRecovery.EntryNumber;WindowsPartitionGuid=ConvertTo-SnapshotGuid $Canonical.WindowsRecovery.PartitionGuid;WindowsLoaderPath=ConvertTo-SnapshotEfiPath $Canonical.WindowsRecovery.LoaderPath;InstalledIdentityDigest=([string]$Canonical.InstalledIdentityDigest).ToLowerInvariant();OwnershipRevision=[string]$Canonical.Manifest.Revision;OwnershipStateSha256=$ownershipHash.ToLowerInvariant();PreviousPersistentDefault=[bool]$Canonical.Manifest.BootOrderChangedByMakeDefault}
    $script:stage='PersistentDefaultSnapshotSerialize';try{$serialized=Get-StateText $snapshot;if([string]::IsNullOrWhiteSpace($serialized)){throw 'SNAPSHOT_SERIALIZATION_FAILED'}}catch{throw 'SNAPSHOT_SERIALIZATION_FAILED'}
    $script:stage='PersistentDefaultSnapshotPersist';try{Write-State $snapshot $persistentSnapshotPath}catch{throw 'SNAPSHOT_WRITE_FAILED'}
    $script:stage='PersistentDefaultSnapshotReadback';try{$read=Get-Content $persistentSnapshotPath -Raw|ConvertFrom-Json}catch{throw 'SNAPSHOT_READBACK_FAILED'}
    $script:stage='PersistentDefaultSnapshotValidation';$null=Test-PersistentDefaultSnapshotReadback $snapshot $read;return $read
}
function Get-PersistentDefaultRollbackContext([object]$Canonical,[string]$OwnedRoot){
    $script:stage='PersistentDefaultOwnershipStateLoad'
    $efiPath=Join-Path $OwnedRoot 'ownership-manifest.json';if(-not[IO.File]::Exists($efiPath)-or-not[IO.File]::Exists($ownershipStatePath)){throw 'OWNERSHIP_REQUIRED_FIELD_MISSING'}
    try{$efiText=[IO.File]::ReadAllText($efiPath);$stateText=[IO.File]::ReadAllText($ownershipStatePath);$efiHash=Get-Hash $efiPath;$stateHash=Get-Hash $ownershipStatePath}catch{throw 'OWNERSHIP_STATE_READ_FAILED'}
    if($efiHash-cne$stateHash){throw 'OWNERSHIP_HASH_MISMATCH'}
    try{$efiManifest=$efiText|ConvertFrom-Json;$stateManifest=$stateText|ConvertFrom-Json}catch{throw 'OWNERSHIP_STATE_JSON_INVALID'}
    foreach($name in 'SchemaVersion','Revision','TargetEspPartitionGuid','FirmwareEntryName','FirmwareEntryNumber'){
        if($name-notin$efiManifest.PSObject.Properties.Name-or$name-notin$stateManifest.PSObject.Properties.Name-or$name-notin$Canonical.Manifest.PSObject.Properties.Name){throw 'OWNERSHIP_REQUIRED_FIELD_MISSING'}
    }
    if([string]$efiManifest.SchemaVersion-cne[string]$stateManifest.SchemaVersion-or[string]$efiManifest.SchemaVersion-cne[string]$Canonical.Manifest.SchemaVersion-or
       [string]$efiManifest.Revision-cne[string]$stateManifest.Revision-or[string]$efiManifest.Revision-cne[string]$Canonical.Manifest.Revision-or
       [string]$efiManifest.TargetEspPartitionGuid-cne[string]$stateManifest.TargetEspPartitionGuid-or[string]$efiManifest.TargetEspPartitionGuid-cne[string]$Canonical.Manifest.TargetEspPartitionGuid-or
       [string]$efiManifest.FirmwareEntryName-cne[string]$stateManifest.FirmwareEntryName-or[string]$efiManifest.FirmwareEntryName-cne[string]$Canonical.Manifest.FirmwareEntryName-or
       [int]$efiManifest.FirmwareEntryNumber-ne[int]$stateManifest.FirmwareEntryNumber-or[int]$efiManifest.FirmwareEntryNumber-ne[int]$Canonical.Manifest.FirmwareEntryNumber){throw 'OWNERSHIP_IDENTITY_MISMATCH'}
    $snapshotText=$null;$snapshotDisposition='NotPresent'
    if([IO.File]::Exists($persistentSnapshotPath)){
        $script:stage='PersistentDefaultHistoricalSnapshotCompatibility'
        try{$candidateText=[IO.File]::ReadAllText($persistentSnapshotPath);$candidate=$candidateText|ConvertFrom-Json;if([string]$candidate.SchemaVersion-ceq'v9-persistent-default-snapshot-1'-and[string]$candidate.InstalledIdentityDigest-ceq[string]$Canonical.InstalledIdentityDigest-and[int]$candidate.SecretoBootEntryNumber-eq[int]$Canonical.Identity.EntryNumber-and[string]$candidate.SecretoBootPartitionGuid-ceq[string]$Canonical.Identity.PartitionGuid){$snapshotText=$candidateText;$snapshotDisposition='PreservedCurrent'}else{$snapshotDisposition='DiscardedStale'}}catch{$snapshotDisposition='DiscardedInvalid'}
    }
    return [pscustomobject]@{EfiManifestText=$efiText;StateManifestText=$stateText;SnapshotText=$snapshotText;SnapshotDisposition=$snapshotDisposition}
}
function Test-CurrentOneTimeVerification([object]$Canonical){if(-not[IO.File]::Exists($statePath)){throw 'CURRENT_ONE_TIME_TEST_REQUIRED'};try{$test=Get-Content $statePath -Raw|ConvertFrom-Json}catch{throw 'CURRENT_ONE_TIME_TEST_REQUIRED'};if($test.BootNextVerified-ne$true-or[string]$test.TestInstalledIdentityDigest-cne[string]$Canonical.InstalledIdentityDigest-or[int]$test.TestFirmwareEntryNumber-ne[int]$Canonical.Identity.EntryNumber-or[string]$test.TestPartitionGuid-cne[string]$Canonical.Identity.PartitionGuid-or[string]$test.TestRefindSha256-cne[string]$Canonical.Manifest.InstalledFiles.'refind_x64.efi'-or[string]$test.TestInstalledRevision-cne[string]$Canonical.Manifest.Revision){throw 'CURRENT_ONE_TIME_TEST_STALE'};if($Canonical.BootNext.Length-ne0){throw 'CURRENT_ONE_TIME_TEST_NOT_CONSUMED'};return $true}
function Get-CompatibilityBootOrderFirst([object]$Value){try{$bytes=[byte[]]@($Value)}catch{throw 'COMPATIBILITY_STATE_INVALID'};if($bytes.Length-lt2-or($bytes.Length%2)-ne0){throw 'COMPATIBILITY_STATE_INVALID'};return [uint16](([uint16]$bytes[0])-bor(([uint16]$bytes[1])-shl 8))}
function Get-CurrentFirmwareDisplayOrderFirstIdentifier {
    $exe=Join-Path $env:SystemRoot 'System32\bcdedit.exe'
    if(-not[IO.File]::Exists($exe)){throw 'WINDOWS_FIRMWARE_MANAGER_UNAVAILABLE'}
    try{
        $captured=@(& $exe /enum '{fwbootmgr}' 2>&1)
        $exitCode=[int]$LASTEXITCODE
    }catch{
        $script:resolverDiagnostic=('Command='+$exe+' /enum {fwbootmgr}; DirectInvocationException='+([string]$_.Exception.Message -replace'[\r\n\t]+',' '))
        throw 'WINDOWS_FIRMWARE_INVENTORY_QUERY_FAILED'
    }
    $text=(($captured|ForEach-Object{[string]$_}) -join [Environment]::NewLine)
    $compact=($text-replace'[\r\n\t]+',' ').Trim();if($compact.Length-gt700){$compact=$compact.Substring(0,700)}
    if($exitCode-ne0){$script:resolverDiagnostic=('Command='+$exe+' /enum {fwbootmgr}; ExitCode='+$exitCode+'; Output='+$compact);throw 'WINDOWS_FIRMWARE_INVENTORY_QUERY_FAILED'}
    foreach($item in $captured){
        $line=[string]$item
        $m=[regex]::Match($line,'^\s*displayorder\s+(\{[^}]+\})\s*$',[Text.RegularExpressions.RegexOptions]::IgnoreCase)
        if($m.Success){
            $identifier=[string]$m.Groups[1].Value
            $script:resolverDiagnostic=('Command='+$exe+' /enum {fwbootmgr}; ExitCode=0; FirstDisplayOrder='+$identifier+'; Output='+$compact)
            return $identifier
        }
    }
    $script:resolverDiagnostic=('Command='+$exe+' /enum {fwbootmgr}; ExitCode=0; FirstDisplayOrder=MISSING; Output='+$compact)
    throw 'WINDOWS_FIRMWARE_DISPLAYORDER_MISSING'
}
function Test-WindowsFirstCompatibilityPreflight([object]$Canonical,[object]$Manifest,[object]$Core){
    $script:stage='WindowsFirstCompatibilityIdentityVerification';try{$null=Test-CurrentOneTimeVerification $Canonical}catch{$reason=Get-SafeReason $_;if($reason-ceq'UNEXPECTED_OPERATION_FAILURE'){throw 'COMPATIBILITY_IDENTITY_MISMATCH'};throw $reason}
    $script:stage='WindowsFirstCompatibilityStateVerification';try{$changed=$Manifest.PSObject.Properties['BootOrderChangedByMakeDefault'];$verifiedUtc=$Manifest.PSObject.Properties['PersistentDefaultVerifiedUtc'];$mode=$Manifest.PSObject.Properties['WindowsFirstCompatibilityMode'];if($null-eq$changed){throw 'COMPATIBILITY_STATE_INVALID'};$priorEvidence=([bool]$changed.Value)-or($null-ne$verifiedUtc-and-not[string]::IsNullOrWhiteSpace([string]$verifiedUtc.Value));if(-not$priorEvidence){throw 'COMPATIBILITY_PRECONDITION_MISSING'};if($null-ne$mode-and[bool]$mode.Value){throw 'WINDOWS_FIRST_COMPATIBILITY_ALREADY_ENABLED'}}catch{$reason=Get-SafeReason $_;if($reason-ceq'UNEXPECTED_OPERATION_FAILURE'){throw 'COMPATIBILITY_STATE_INVALID'};throw $reason}
    $script:stage='WindowsFirstCompatibilityFirmwareVerification';try{$windows=Get-WindowsFirmwareEvidence $Core ([byte[]]@($Canonical.BootOrder));$rawFirst=Get-CompatibilityBootOrderFirst $Canonical.BootOrder;$bcdFirst=Get-CurrentFirmwareDisplayOrderFirstIdentifier;if([string]$bcdFirst-ine'{bootmgr}'){$script:resolverDiagnostic=$script:resolverDiagnostic+'; RawBootOrderFirst=Boot'+([uint16]$rawFirst).ToString('X4')+'; ExpectedBcdFirst={bootmgr}';throw 'COMPATIBILITY_PRECONDITION_MISSING'}}catch{$reason=Get-SafeReason $_;if($reason-ceq'UNEXPECTED_OPERATION_FAILURE'){throw 'COMPATIBILITY_IDENTITY_MISMATCH'};throw $reason}
    $script:stage='WindowsFirstCompatibilityBootManagerPathVerification';try{$path=Get-NativeWindowsBootManagerPath}catch{$reason=Get-SafeReason $_;if($reason-ceq'UNEXPECTED_OPERATION_FAILURE'){throw 'WINDOWS_BOOTMGR_QUERY_FAILED'};throw $reason};if([string]::IsNullOrWhiteSpace([string]$path)){throw 'WINDOWS_BOOTMGR_PATH_MISSING'};if([string]$path-ine'\EFI\Microsoft\Boot\bootmgfw.efi'){throw 'WINDOWS_NATIVE_PATH_MISMATCH'}
    return [pscustomobject]@{Windows=$windows;NativePath=[string]$path;FirstEntry=[uint16]$rawFirst;FirmwareDisplayOrderFirst=[string]$bcdFirst}
}
function Read-CurrentPersistentSnapshot([object]$Canonical){if(-not[IO.File]::Exists($persistentSnapshotPath)){throw 'SNAPSHOT_READBACK_FAILED'};try{$snapshot=Get-Content $persistentSnapshotPath -Raw|ConvertFrom-Json}catch{throw 'SNAPSHOT_READBACK_FAILED'};try{if([string]$snapshot.SchemaVersion-cne'v9-persistent-default-snapshot-1'-or[string]$snapshot.InstalledIdentityDigest-cne([string]$Canonical.InstalledIdentityDigest).ToLowerInvariant()-or[int]$snapshot.SecretoBootEntryNumber-ne[int]$Canonical.Identity.EntryNumber-or(ConvertTo-SnapshotGuid $snapshot.SecretoBootPartitionGuid)-cne(ConvertTo-SnapshotGuid $Canonical.Identity.PartitionGuid)-or(ConvertTo-SnapshotEfiPath $snapshot.SecretoBootLoaderPath)-cne(ConvertTo-SnapshotEfiPath '\EFI\SecretoBoot\refind_x64.efi')-or[int]$snapshot.WindowsEntryNumber-ne[int]$Canonical.WindowsRecovery.EntryNumber-or(ConvertTo-SnapshotGuid $snapshot.WindowsPartitionGuid)-cne(ConvertTo-SnapshotGuid $Canonical.WindowsRecovery.PartitionGuid)-or(ConvertTo-SnapshotEfiPath $snapshot.WindowsLoaderPath)-cne(ConvertTo-SnapshotEfiPath $Canonical.WindowsRecovery.LoaderPath)){throw 'STALE_REPAIRED_FIRMWARE_IDENTITY'}}catch{throw 'STALE_REPAIRED_FIRMWARE_IDENTITY'};return $snapshot}
function Test-OwnedFiles([object]$Manifest,[string]$OwnedRoot){foreach($property in $Manifest.InstalledFiles.PSObject.Properties){$relative=[string]$property.Name;if($relative-notmatch'^[A-Za-z0-9._/-]+$'-or$relative-match'(^|/)\.\.(/|$)'){throw 'OWNED_PATH_DENIED'};$path=[IO.Path]::GetFullPath((Join-Path $OwnedRoot $relative));if(-not$path.StartsWith([IO.Path]::GetFullPath($OwnedRoot)+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)-or-not[IO.File]::Exists($path)-or(Get-Hash $path)-cne[string]$property.Value){throw 'OWNED_FILE_IDENTITY_DENIED'}}}
function Test-EfiOwnershipManifest([object]$Manifest,[string]$OwnedRoot){$path=Join-Path $OwnedRoot 'ownership-manifest.json';if(-not[IO.File]::Exists($path)){throw 'EFI_OWNERSHIP_MANIFEST_MISSING'};if(-not[IO.File]::Exists($ownershipStatePath)){throw 'OWNERSHIP_STATE_MISSING'};$efiHash=Get-Hash $path;$stateHash=Get-Hash $ownershipStatePath;if($efiHash-cne$stateHash){throw 'EFI_OWNERSHIP_MANIFEST_IDENTITY_DENIED'};try{$state=Get-Content $ownershipStatePath -Raw|ConvertFrom-Json}catch{throw 'OWNERSHIP_STATE_JSON_INVALID'};foreach($name in 'SchemaVersion','Revision','TargetEspPartitionGuid','FirmwareEntryName','FirmwareEntryNumber'){if($name-notin$state.PSObject.Properties.Name-or$name-notin$Manifest.PSObject.Properties.Name){throw 'OWNERSHIP_REQUIRED_FIELD_MISSING'}};if([string]$state.SchemaVersion-cne[string]$Manifest.SchemaVersion-or[string]$state.Revision-cne[string]$Manifest.Revision-or[string]$state.TargetEspPartitionGuid-cne[string]$Manifest.TargetEspPartitionGuid-or[string]$state.FirmwareEntryName-cne[string]$Manifest.FirmwareEntryName-or[int]$state.FirmwareEntryNumber-ne[int]$Manifest.FirmwareEntryNumber){throw 'EFI_OWNERSHIP_MANIFEST_IDENTITY_DENIED'}}
function Commit-InstalledFirmwareIdentity([object]$Manifest,[string]$OwnedRoot,[object]$FirmwareResult){
    $efiPath=Join-Path $OwnedRoot 'ownership-manifest.json';$oldEfi=Get-Content $efiPath -Raw;$oldState=Get-Content $ownershipStatePath -Raw
    try{$Manifest.FirmwareEntryName=[string]$FirmwareResult.EntryName;$Manifest.FirmwareEntryNumber=[int]$FirmwareResult.EntryNumber;$Manifest.FirmwareLoadOptionBase64=[Convert]::ToBase64String([byte[]]$FirmwareResult.LoadOption);$Manifest.Revision=$revision;$Manifest|Add-Member -NotePropertyName FirmwareEntryRepairedUtc -NotePropertyValue ([DateTime]::UtcNow.ToString('o')) -Force;Write-State $Manifest $efiPath;Write-State $Manifest $ownershipStatePath;if((Get-Hash $efiPath)-cne(Get-Hash $ownershipStatePath)){throw 'OWNERSHIP_COMMIT_READBACK_MISMATCH'};$verified=Read-Ownership;if([int]$verified.FirmwareEntryNumber-ne[int]$FirmwareResult.EntryNumber-or[string]$verified.FirmwareEntryName-cne[string]$FirmwareResult.EntryName-or[string]$verified.FirmwareLoadOptionBase64-cne[Convert]::ToBase64String([byte[]]$FirmwareResult.LoadOption)){throw 'OWNERSHIP_COMMIT_READBACK_MISMATCH'};Test-EfiOwnershipManifest $verified $OwnedRoot;return $verified}catch{try{[IO.File]::WriteAllText($efiPath,$oldEfi,[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText($ownershipStatePath,$oldState,[Text.UTF8Encoding]::new($false))}catch{throw 'OWNERSHIP_COMMIT_ROLLBACK_FAILED'};throw 'OWNERSHIP_COMMIT_FAILED'}
}
function Invoke-InstalledFirmwareRepair([object]$Manifest,[object]$Identity,[object]$Access,[string]$OwnedRoot){
    $script:stage='InstalledFirmwareRepairPreflight';if($ConsentPhrase-cne'REPAIR_SECRETOBOOT_FIRMWARE_ENTRY'){throw 'OWNED_FIRMWARE_REPAIR_CONSENT_DENIED'};Test-OwnedFiles $Manifest $OwnedRoot;Test-EfiOwnershipManifest $Manifest $OwnedRoot;$loader=Join-Path $OwnedRoot 'refind_x64.efi';if(-not[IO.File]::Exists($loader)-or'refind_x64.efi'-notin$Manifest.InstalledFiles.PSObject.Properties.Name-or(Get-Hash $loader)-cne[string]$Manifest.InstalledFiles.'refind_x64.efi'){throw 'OWNED_LOADER_HASH_MISMATCH'}
    $before=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootOrder');$partition=$Access.Resolved.Partition;$disk=$Access.Resolved.Disk;$sector=[uint64]$disk.LogicalSectorSize;if($sector-lt512-or$partition.PartitionNumber-lt1-or$partition.Offset-lt$sector-or$partition.Size-lt$sector){throw 'OWNED_FIRMWARE_IDENTITY_MISMATCH'}
    $efiManifestPath=Join-Path $OwnedRoot 'ownership-manifest.json';$oldEfiManifest=Get-Content $efiManifestPath -Raw;$oldStateManifest=Get-Content $ownershipStatePath -Raw;$oldTransaction=if([IO.File]::Exists($statePath)){Get-Content $statePath -Raw}else{$null};$oldSnapshot=if([IO.File]::Exists($persistentSnapshotPath)){Get-Content $persistentSnapshotPath -Raw}else{$null};$firmware=$null;$created=$false;$ownershipCommitted=$false;try{$script:stage='InstalledFirmwareEquivalentEntrySearch';$firmware=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::RepairMissingOwnedEntry([uint32]$partition.PartitionNumber,[uint64]([uint64]$partition.Offset/$sector),[uint64]([uint64]$partition.Size/$sector),[guid]$Identity.PartitionGuid);$created=-not$firmware.ExistingExact;$script:stage=if($created){'InstalledFirmwareEntryCreation'}else{'InstalledFirmwareEntryAdoption'}
        $script:stage='InstalledFirmwareEntryReadback';$actual=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ValidateInstalledEntryIdentity([uint16]$firmware.EntryNumber,[string]$firmware.EntryName,[byte[]]$firmware.LoadOption,[byte[]]$firmware.LoadOption,[guid]$Identity.PartitionGuid);[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ValidateInstalledEntryInventory([uint16]$firmware.EntryNumber,$actual,[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadBootInventory())
        $script:stage='InstalledFirmwareOwnershipCommit';$updated=Commit-InstalledFirmwareIdentity $Manifest $OwnedRoot $firmware;$ownershipCommitted=$true
        $script:stage='InstalledFirmwareRepairVerification';$null=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::VerifyInstalledOwnedEntry([uint16]$firmware.EntryNumber,[string]$firmware.EntryName,[byte[]]$firmware.LoadOption,[guid]$Identity.PartitionGuid);$after=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootOrder');if(-not([Convert]::ToBase64String($after)-ceq[Convert]::ToBase64String($before))){throw 'PERMANENT_BOOT_ORDER_CHANGED_DURING_REPAIR'};$invalidated=[pscustomobject][ordered]@{SchemaVersion='v9-deployment-transaction-1';Revision=$revision;Stage='FirmwareEntryRepaired';TargetEspPartitionGuid=[string]$Identity.PartitionGuid;FirmwareEntryNumber=[int]$firmware.EntryNumber;RollbackRequired=$false;BootNextVerified=$false;InvalidationReason='FIRMWARE_IDENTITY_CHANGED';CompletedUtc=[DateTime]::UtcNow.ToString('o')};Write-State $invalidated $statePath;if([IO.File]::Exists($persistentSnapshotPath)){[IO.File]::Delete($persistentSnapshotPath)}
        return [pscustomobject]@{Reason='OWNED_FIRMWARE_REPAIR_VERIFIED';Message='SecretoBoot firmware entry repaired successfully. Firmware entry: Verified. Runtime: Verified. Theme: FinalRelease.1 / MATCH. No permanent boot order change was made.'}
    }catch{$reason=Get-SafeReason $_;try{if($ownershipCommitted){[IO.File]::WriteAllText($efiManifestPath,$oldEfiManifest,[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText($ownershipStatePath,$oldStateManifest,[Text.UTF8Encoding]::new($false))};if($null-ne$oldTransaction){[IO.File]::WriteAllText($statePath,$oldTransaction,[Text.UTF8Encoding]::new($false))}elseif([IO.File]::Exists($statePath)){[IO.File]::Delete($statePath)};if($null-ne$oldSnapshot){[IO.File]::WriteAllText($persistentSnapshotPath,$oldSnapshot,[Text.UTF8Encoding]::new($false))}elseif([IO.File]::Exists($persistentSnapshotPath)){[IO.File]::Delete($persistentSnapshotPath)};if($created-and$null-ne$firmware){[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::RemoveOwnedEntry([uint16]$firmware.EntryNumber,[byte[]]$firmware.LoadOption)};if($ownershipCommitted-or$created){$script:rollbackStatus='Completed'}}catch{$script:rollbackStatus='Failed';throw 'OWNED_FIRMWARE_REPAIR_ROLLBACK_FAILED'};throw $reason}
}
function Remove-OwnedTree([object]$Manifest,[string]$OwnedRoot){Test-OwnedFiles $Manifest $OwnedRoot;Test-EfiOwnershipManifest $Manifest $OwnedRoot;foreach($relative in @($Manifest.InstalledFiles.PSObject.Properties.Name|Sort-Object Length -Descending)){[IO.File]::Delete((Join-Path $OwnedRoot $relative))};[IO.File]::Delete((Join-Path $OwnedRoot 'ownership-manifest.json'));foreach($dir in @([IO.Directory]::EnumerateDirectories($OwnedRoot,'*',[IO.SearchOption]::AllDirectories)|Sort-Object Length -Descending)){if(-not[IO.Directory]::EnumerateFileSystemEntries($dir).GetEnumerator().MoveNext()){[IO.Directory]::Delete($dir)}};if(-not[IO.Directory]::EnumerateFileSystemEntries($OwnedRoot).GetEnumerator().MoveNext()){[IO.Directory]::Delete($OwnedRoot)}}

function Invoke-InterruptedRecovery {
    if(-not[IO.File]::Exists($statePath)){throw 'RECOVERY_STATE_MISSING'};$tx=Get-Content $statePath -Raw|ConvertFrom-Json;if([string]$tx.SchemaVersion-cne'v9-deployment-transaction-1'-or[string]$tx.Revision-notin$supportedOwnershipRevisions){throw 'RECOVERY_STATE_DENIED'};if([string]$tx.Stage-in@('DeploymentComplete','RollbackComplete','BootNextVerified','FirmwareEntryRepaired')){return [pscustomobject]@{Reason='RECOVERY_NOT_REQUIRED';Message='No incomplete transaction requires recovery.'}}
    $access=$null;try{$script:stage='InterruptedTransactionRecovery';$access=Open-RecoveryAccess $tx;$owned=Join-Path $access.Root 'EFI/SecretoBoot';if($null-ne$tx.FirmwareEntryNumber-and[string]$tx.FirmwareLoadOptionBase64){[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::RemoveOwnedEntry([uint16]$tx.FirmwareEntryNumber,[Convert]::FromBase64String([string]$tx.FirmwareLoadOptionBase64))};if([IO.Directory]::Exists($owned)){$files=if($null-ne$tx.InstalledFiles){$tx.InstalledFiles}else{[pscustomobject]@{}};foreach($property in $files.PSObject.Properties){$path=Join-Path $owned $property.Name;if(-not[IO.File]::Exists($path)-or(Get-Hash $path)-cne[string]$property.Value){throw 'RECOVERY_OWNED_FILE_IDENTITY_DENIED'}};$ownershipPath=Join-Path $owned 'ownership-manifest.json';if([IO.File]::Exists($ownershipPath)){if([string]$tx.OwnershipManifestSha256-notmatch'^[0-9a-f]{64}$'-or(Get-Hash $ownershipPath)-cne[string]$tx.OwnershipManifestSha256){throw 'RECOVERY_OWNERSHIP_MANIFEST_DENIED'};[IO.File]::Delete($ownershipPath)};foreach($property in $files.PSObject.Properties){[IO.File]::Delete((Join-Path $owned $property.Name))};foreach($dir in @([IO.Directory]::EnumerateDirectories($owned,'*',[IO.SearchOption]::AllDirectories)|Sort-Object Length -Descending)){if(-not[IO.Directory]::EnumerateFileSystemEntries($dir).GetEnumerator().MoveNext()){[IO.Directory]::Delete($dir)}};if(-not[IO.Directory]::EnumerateFileSystemEntries($owned).GetEnumerator().MoveNext()){[IO.Directory]::Delete($owned)}};$tx.Stage='RollbackComplete';$tx.RollbackRequired=$false;$tx.TemporaryAccessPath=$null;Write-State $tx $statePath;return [pscustomobject]@{Reason='INTERRUPTED_TRANSACTION_RECOVERED';Message='Only transaction-owned SecretoBoot state was rolled back.'}}finally{if($null-ne$access){Close-PartitionAccess $access}}
}

function Invoke-Install([object]$Envelope,[bool]$SetNextBoot){
    $validation=Test-SbDeploymentEnvelope $Envelope;if(-not$validation.Valid){throw $validation.Reasons[0]};$core=$validation.Core
    $script:stage='FreshInstallHybridResolution';try{$core=Resolve-HybridPlan $core}catch{$reason=Get-SafeReason $_;if($reason-ceq'HYBRID_WINDOWS_TARGET_NOT_FOUND'){throw 'PLAN_WINDOWS_TARGET_UNRESOLVED'};if($reason-ceq'HYBRID_BLISS_TARGET_NOT_FOUND'){throw 'PLAN_BLISS_TARGET_UNRESOLVED'};throw $reason}
    $script:stage='ResolvedPlanValidation';$resolvedValidation=Test-SbResolvedDeploymentCore $core $true;if(-not$resolvedValidation.Valid){throw $resolvedValidation.Reasons[0]}
    $script:stage='ResolvedPlanConfirmation';Confirm-ResolvedFreshInstallPlan $core
    $script:stage='SecurityPreflight';Assert-SecureBootDisabled;Assert-BitLockerPrepared
    $targetAccess=$null;$createdEntry=$null;$createdLoadOption=$null;$installed=[ordered]@{};$tx=$null
    try{
        $script:stage='TargetEspAccess';$targetAccess=Open-PartitionAccess ([guid]$core.TargetEspPartitionGuid);$owned=Join-Path $targetAccess.Root 'EFI/SecretoBoot';if([IO.Directory]::Exists($owned)){throw 'EXISTING_SECRETOBOOT_DIRECTORY_DENIED'}
        $tx=[pscustomobject][ordered]@{SchemaVersion='v9-deployment-transaction-1';Revision=$revision;PlanDigest=$Envelope.PlanDigest;Stage='Preflight';TargetEspPartitionGuid=[string]$core.TargetEspPartitionGuid;TemporaryAccessPath=if($targetAccess.Temporary){[string]$targetAccess.AccessPath}else{$null};RollbackRequired=$false;StartedUtc=[DateTime]::UtcNow.ToString('o');CompletedUtc=$null;PreviousBootOrderBase64=$null;ForeignLoaderHashes=$null;InstalledFiles=$null;FirmwareEntryName=$null;FirmwareEntryNumber=$null;FirmwareLoadOptionBase64=$null;OwnershipManifestSha256=$null;BootNextVerified=$false};Write-State $tx $statePath
        $script:stage='BackupPreparation';$foreign=[ordered]@{};foreach($entry in @($core.BootEntries)){$sourceAccess=$null;try{$sourceAccess=if(([guid]$entry.PartitionGuid)-eq([guid]$core.TargetEspPartitionGuid)){$targetAccess}else{Open-PartitionAccess ([guid]$entry.PartitionGuid)};$loader=Join-Path $sourceAccess.Root ([string]$entry.LoaderPath).TrimStart('\');if(-not[IO.File]::Exists($loader)){throw 'SOURCE_LOADER_MISSING'};$foreign[([string]$entry.PartitionGuid+'|'+[string]$entry.LoaderPath)]=Get-Hash $loader}finally{if($null-ne$sourceAccess-and$sourceAccess-ne$targetAccess){Close-PartitionAccess $sourceAccess}}};$bootOrder=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootOrder');$tx.Stage='BackupPrepared';$tx.PreviousBootOrderBase64=[Convert]::ToBase64String($bootOrder);$tx.ForeignLoaderHashes=$foreign;Write-State $tx $statePath
        $script:stage='EfiFileInstallation';[IO.Directory]::CreateDirectory($owned)|Out-Null;foreach($source in [IO.Directory]::EnumerateFiles($assetsRoot,'*',[IO.SearchOption]::AllDirectories)){$relative=[IO.Path]::GetRelativePath($assetsRoot,$source).Replace('\','/');$destination=Join-Path $owned $relative;[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($destination))|Out-Null;[IO.File]::Copy($source,$destination,$false);$installed[$relative]=Get-Hash $destination};$configPath=Join-Path $owned 'refind.conf';[IO.File]::WriteAllText($configPath,[string]$core.RefindConfig,[Text.UTF8Encoding]::new($false));$installed['refind.conf']=Get-Hash $configPath;$tx.Stage='FilesInstalled';$tx.RollbackRequired=$true;$tx.InstalledFiles=$installed;Write-State $tx $statePath
        $script:stage='EfiFileVerification';foreach($property in $installed.GetEnumerator()){if((Get-Hash (Join-Path $owned $property.Key))-cne$property.Value){throw 'INSTALLED_FILE_READBACK_DENIED'}};$tx.Stage='FilesVerified';Write-State $tx $statePath
        $script:stage='FirmwareEntryCreation';$partition=$targetAccess.Resolved.Partition;$disk=$targetAccess.Resolved.Disk;$sector=[uint64]$disk.LogicalSectorSize;$fw=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::CreateOrReuseUnorderedEntry([uint32]$partition.PartitionNumber,[uint64]([uint64]$partition.Offset/$sector),[uint64]([uint64]$partition.Size/$sector),[guid]$core.TargetEspPartitionGuid);if(-not$fw.Success){throw $fw.ReasonCode};if($fw.ExistingExact){throw 'PREEXISTING_SECRETOBOOT_ENTRY_UNOWNED_DENIED'};$createdEntry=[uint16]$fw.EntryNumber;$createdLoadOption=[byte[]]$fw.LoadOption;[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::VerifyOwnedEntry($createdEntry,$createdLoadOption);$afterCreation=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootOrder');if(-not([Convert]::ToBase64String($afterCreation)-ceq[Convert]::ToBase64String($bootOrder))){throw 'PERMANENT_BOOT_ORDER_CHANGED_DURING_INSTALL'}
        $tx.Stage='FirmwareEntryCreated';$tx.FirmwareEntryName=$fw.EntryName;$tx.FirmwareEntryNumber=[int]$fw.EntryNumber;$tx.FirmwareLoadOptionBase64=[Convert]::ToBase64String($createdLoadOption);$tx.PreviousBootOrderBase64=[Convert]::ToBase64String($fw.PreviousBootOrder)
        $ownership=[pscustomobject][ordered]@{SchemaVersion='v9-ownership-manifest-1';OwnershipVerified=$true;Revision=$revision;ThemeRevision='FinalRelease.1';ThemeDeployment='MATCH';RefindVersion='0.14.2';InstalledUtc=[DateTime]::UtcNow.ToString('o');TargetEspPartitionGuid=[string]$core.TargetEspPartitionGuid;InstalledFiles=[pscustomobject]$installed;FirmwareEntryName=$fw.EntryName;FirmwareEntryNumber=[int]$fw.EntryNumber;FirmwareLoadOptionBase64=[Convert]::ToBase64String($createdLoadOption);PreviousBootOrderBase64=[Convert]::ToBase64String($fw.PreviousBootOrder);ForeignLoaderHashes=[pscustomobject]$foreign;BootOrderChangedByMakeDefault=$false};$ownershipText=Get-StateText $ownership;$tx.OwnershipManifestSha256=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($ownershipText))).ToLowerInvariant();Write-State $tx $statePath;[IO.File]::WriteAllText((Join-Path $owned 'ownership-manifest.json'),$ownershipText,[Text.UTF8Encoding]::new($false));if((Get-Hash (Join-Path $owned 'ownership-manifest.json'))-cne$tx.OwnershipManifestSha256){throw 'OWNERSHIP_MANIFEST_READBACK_DENIED'};Write-State $ownership $ownershipStatePath
        if($SetNextBoot){$script:stage='BootNextAssignment';[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::SetBootNextAndVerify($createdEntry,$createdLoadOption);$afterBootNext=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootOrder');if(-not([Convert]::ToBase64String($afterBootNext)-ceq[Convert]::ToBase64String($bootOrder))){throw 'PERMANENT_BOOT_ORDER_CHANGED_DURING_TEST'};$installedIdentity=[pscustomobject]@{EntryName=$fw.EntryName;EntryNumber=[int]$fw.EntryNumber;PartitionGuid=[guid]$core.TargetEspPartitionGuid;LoadOption=[byte[]]$createdLoadOption};$tx.BootNextVerified=$true;$tx.Stage='BootNextVerified';$tx|Add-Member -NotePropertyName TestInstalledIdentityDigest -NotePropertyValue (Get-InstalledIdentityDigest $ownership $installedIdentity) -Force;$tx|Add-Member -NotePropertyName TestFirmwareEntryNumber -NotePropertyValue ([int]$fw.EntryNumber) -Force;$tx|Add-Member -NotePropertyName TestPartitionGuid -NotePropertyValue ([string]$core.TargetEspPartitionGuid) -Force;$tx|Add-Member -NotePropertyName TestRefindSha256 -NotePropertyValue ([string]$ownership.InstalledFiles.'refind_x64.efi') -Force;$tx|Add-Member -NotePropertyName TestInstalledRevision -NotePropertyValue ([string]$ownership.Revision) -Force;Write-State $tx $statePath}
        $script:stage='TemporaryAccessRelease';Close-PartitionAccess $targetAccess;$targetAccess=$null;$tx.TemporaryAccessPath=$null
        $tx.Stage='DeploymentComplete';$tx.RollbackRequired=$false;$tx.CompletedUtc=[DateTime]::UtcNow.ToString('o');Write-State $tx $statePath;$linuxCount=@($core.BootEntries|Where-Object{$_.Family-ceq'Linux'}).Count;return [pscustomobject]@{Reason=if($SetNextBoot){'TEST_BOOT_READY_VERIFIED'}else{'INSTALLATION_VERIFIED'};Message=if($SetNextBoot){'Windows: Ready; BlissOS: Ready; Linux entries: '+$linuxCount+'. The next restart will boot SecretoBoot once. The permanent default boot order was not changed.'}else{'SecretoBoot files and firmware entry were installed and verified.'}}
    }catch{$originalReason=Get-SafeReason $_;$rollbackFailed=$false;$rollbackNeeded=($null-ne$createdEntry)-or($null-ne$tx-and$tx.RollbackRequired);if($null-ne$createdEntry){try{[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::RemoveOwnedEntry($createdEntry,$createdLoadOption)}catch{$rollbackFailed=$true}};if($null-ne$targetAccess-and$null-ne$tx-and$tx.RollbackRequired){$owned=Join-Path $targetAccess.Root 'EFI/SecretoBoot';if([IO.Directory]::Exists($owned)){try{foreach($relative in @($installed.Keys)){[IO.File]::Delete((Join-Path $owned $relative))};$ownershipPath=Join-Path $owned 'ownership-manifest.json';if([IO.File]::Exists($ownershipPath)){[IO.File]::Delete($ownershipPath)};foreach($dir in @([IO.Directory]::EnumerateDirectories($owned,'*',[IO.SearchOption]::AllDirectories)|Sort-Object Length -Descending)){if(-not[IO.Directory]::EnumerateFileSystemEntries($dir).GetEnumerator().MoveNext()){[IO.Directory]::Delete($dir)}};if(-not[IO.Directory]::EnumerateFileSystemEntries($owned).GetEnumerator().MoveNext()){[IO.Directory]::Delete($owned)}}catch{$rollbackFailed=$true}}};if($null-ne$tx){$tx.Stage=if($rollbackFailed){'RollbackFailed'}else{'RollbackComplete'};$tx.RollbackRequired=$rollbackFailed;try{Write-State $tx $statePath}catch{$rollbackFailed=$true}};$script:rollbackStatus=if($rollbackFailed){'Failed'}elseif($rollbackNeeded){'Completed'}else{'Not required'};if($rollbackFailed){throw 'ROLLBACK_INCOMPLETE_REQUIRES_RECOVERY'};throw $originalReason
    }finally{if($null-ne$targetAccess){Close-PartitionAccess $targetAccess}}
}

function Invoke-UpgradeAndTest([object]$Envelope){
    $validation=Test-SbDeploymentEnvelope $Envelope;if(-not$validation.Valid){throw $validation.Reasons[0]};$core=Resolve-HybridPlan $validation.Core
    $script:stage='SecurityPreflight';Assert-SecureBootDisabled;Assert-BitLockerPrepared
    $manifest=Read-Ownership;if((ConvertTo-ResolvedGuid $manifest.TargetEspPartitionGuid)-cne(ConvertTo-ResolvedGuid $core.TargetEspPartitionGuid)){throw 'UPGRADE_TARGET_ESP_IDENTITY_DENIED'}
    $access=$null;try{
        $script:stage='OwnedInstallationVerification';$access=Open-PartitionAccess ([guid]$manifest.TargetEspPartitionGuid);$owned=Join-Path $access.Root 'EFI/SecretoBoot';Test-OwnedFiles $manifest $owned;Test-EfiOwnershipManifest $manifest $owned
        $entry=[uint16]$manifest.FirmwareEntryNumber;$loadOption=[Convert]::FromBase64String([string]$manifest.FirmwareLoadOptionBase64);[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::VerifyOwnedEntry($entry,$loadOption)
        $before=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootOrder');$backupRoot=Join-Path $stateRoot ('upgrade-backups/'+[guid]::NewGuid().ToString('N'))
        $script:stage='OwnedRuntimeUpgrade';$upgrade=Invoke-SbOwnedRuntimeUpgrade -OldManifest $manifest -OwnedRoot $owned -AssetsRoot $assetsRoot -ConfigText ([string]$core.RefindConfig) -StateManifestPath $ownershipStatePath -BackupRoot $backupRoot -NewRevision $revision -ThemeRevision 'FinalRelease.1' -SupportedOldRevisions $supportedOwnershipRevisions
        if([string]$upgrade.ThemeDeployment-cne'MATCH'-or[string]$upgrade.ThemeRevision-cne'FinalRelease.1'){throw 'UPGRADE_THEME_VERIFICATION_DENIED'}
        $script:stage='TemporaryAccessRelease';Close-PartitionAccess $access;$access=$null
        $script:stage='BootNextAssignment';[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::SetBootNextAndVerify($entry,$loadOption);$after=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootOrder');if(-not([Convert]::ToBase64String($after)-ceq[Convert]::ToBase64String($before))){throw 'PERMANENT_BOOT_ORDER_CHANGED_DURING_TEST'}
        $currentManifest=Read-Ownership;$currentIdentity=Get-InstalledFirmwareIdentity $currentManifest;$tx=[pscustomobject][ordered]@{SchemaVersion='v9-deployment-transaction-1';Revision=$revision;Stage='DeploymentComplete';TargetEspPartitionGuid=[string]$currentIdentity.PartitionGuid;FirmwareEntryNumber=[int]$currentIdentity.EntryNumber;RollbackRequired=$false;BootNextVerified=$true;TestInstalledIdentityDigest=Get-InstalledIdentityDigest $currentManifest $currentIdentity;TestFirmwareEntryNumber=[int]$currentIdentity.EntryNumber;TestPartitionGuid=[string]$currentIdentity.PartitionGuid;TestRefindSha256=[string]$currentManifest.InstalledFiles.'refind_x64.efi';TestInstalledRevision=[string]$currentManifest.Revision;ThemeRevision='FinalRelease.1';ThemeDeployment='MATCH';CompletedUtc=[DateTime]::UtcNow.ToString('o')};Write-State $tx $statePath
        [pscustomobject]@{Reason='FINALRELEASE_THEME_UPGRADED_TEST_BOOT_READY';Message='The owned SecretoBoot runtime was upgraded to FinalRelease.1 and verified. The next restart will test the updated theme once.'}
    }finally{if($null-ne$access){Close-PartitionAccess $access}}
}

try{
    Assert-Administrator;Assert-PackageIntegrity;Import-Module $deploymentModule -Force;Import-Module $hybridModule -Force;Import-Module $upgradeModule -Force;Import-Module $commandResolutionModule -Force;Import-TrustedStorage;Add-Type -Path $firmwareSource
    switch($Action){
        'Install' {$stage='PlanValidation';if($ConsentPhrase-cne'INSTALL_SECRETOBOOT_EXPERIMENTAL'-or-not[IO.File]::Exists($PlanPath)){throw 'FINAL_INSTALL_CONSENT_DENIED'};$result=Invoke-Install (Get-Content $PlanPath -Raw|ConvertFrom-Json) $false}
        'InstallAndTestNextBoot' {$stage='PlanValidation';if($ConsentPhrase-cne'INSTALL_AND_TEST_SECRETOBOOT_NEXT_BOOT'-or-not[IO.File]::Exists($PlanPath)){throw 'INSTALL_AND_TEST_CONSENT_DENIED'};$result=Invoke-Install (Get-Content $PlanPath -Raw|ConvertFrom-Json) $true}
        'UpgradeAndTestNextBoot' {$stage='PlanValidation';if($ConsentPhrase-cne'UPGRADE_FINALPOLISH_AND_TEST_NEXT_BOOT'-or-not[IO.File]::Exists($PlanPath)){throw 'UPGRADE_AND_TEST_CONSENT_DENIED'};$result=Invoke-UpgradeAndTest (Get-Content $PlanPath -Raw|ConvertFrom-Json)}
        'Recover' {if($ConsentPhrase-cne'RECOVER_SECRETOBOOT_TRANSACTION'){throw 'RECOVERY_CONSENT_DENIED'};$result=Invoke-InterruptedRecovery}
        default {
            $validatedDefaultCore=$null;if($Action-in@('TestNextBoot','MakeDefault','EnableWindowsFirstCompatibility','RestorePreviousDefault')){$stage=switch($Action){'TestNextBoot'{'TestNextPlanValidation'};'MakeDefault'{'PersistentDefaultPlanValidation'};'EnableWindowsFirstCompatibility'{'WindowsFirstCompatibilityPlanValidation'};default{'WindowsRestorePlanValidation'}};if(-not[IO.File]::Exists($PlanPath)){throw $(switch($Action){'TestNextBoot'{'TEST_NEXT_CURRENT_PLAN_REQUIRED'};'MakeDefault'{'PERSISTENT_DEFAULT_PLAN_REQUIRED'};'EnableWindowsFirstCompatibility'{'WINDOWS_FIRST_COMPATIBILITY_PLAN_REQUIRED'};default{'WINDOWS_RESTORE_PLAN_REQUIRED'}})};$defaultValidation=Test-SbDeploymentEnvelope (Get-Content $PlanPath -Raw|ConvertFrom-Json);if(-not$defaultValidation.Valid){throw $defaultValidation.Reasons[0]};$validatedDefaultCore=Resolve-HybridPlan $defaultValidation.Core}
            $stage='InstalledOwnershipStateLoad';try{$manifest=Read-Ownership;$identity=Get-InstalledFirmwareIdentity $manifest}catch{$reason=Get-SafeReason $_;if($reason-ceq'UNEXPECTED_OPERATION_FAILURE'){throw 'INSTALLED_OWNERSHIP_STATE_RUNTIME_FAILED'};throw $reason}
            $access=$null;try{$stage='InstalledTargetCorrelation';if($null-ne$validatedDefaultCore-and(ConvertTo-ResolvedGuid $manifest.TargetEspPartitionGuid)-cne(ConvertTo-ResolvedGuid $validatedDefaultCore.TargetEspPartitionGuid)){throw 'PERSISTENT_DEFAULT_TARGET_ESP_IDENTITY_DENIED'}
                $stage='InstalledTargetAccess';try{$access=Open-PartitionAccess $identity.PartitionGuid}catch{$reason=Get-SafeReason $_;if($reason-ceq'UNEXPECTED_OPERATION_FAILURE'){throw 'INSTALLED_TARGET_ACCESS_RUNTIME_FAILED'};throw $reason}
                $owned=Join-Path $access.Root 'EFI/SecretoBoot';$allowMissing=$Action-in@('RepairFirmwareEntry','Uninstall','Rollback');try{$canonical=Get-CanonicalInstalledState $manifest $identity $access $owned $validatedDefaultCore $allowMissing}catch{$reason=Get-SafeReason $_;if($reason-ceq'UNEXPECTED_OPERATION_FAILURE'){throw 'CANONICAL_INSTALLED_STATE_RUNTIME_FAILED'};throw $reason}
                $entry=[uint16]$identity.EntryNumber;$entryName=[string]$identity.EntryName;$loadOption=[byte[]]$identity.LoadOption;$targetPartitionGuid=[guid]$identity.PartitionGuid;$firmwareEntryMissing=[string]$canonical.FirmwareStatus-ceq'Missing'
                switch($Action){
                    'RepairFirmwareEntry' {if(-not$firmwareEntryMissing){throw 'OWNED_FIRMWARE_REPAIR_NOT_REQUIRED'};$result=Invoke-InstalledFirmwareRepair $manifest $identity $access $owned}
                    'TestNextBoot' {$stage='ThemeDeploymentVerification';if(-not$canonical.ThemeVerified){throw 'THEME_DEPLOYMENT_STALE_UPGRADE_REQUIRED'};if($canonical.BootNext.Length-ne0){throw 'BOOTNEXT_EXISTING_STATE_DENIED'};$stage='TemporaryAccessRelease';Close-PartitionAccess $access;$access=$null;$stage='BootNextAssignment';if($ConsentPhrase-cne'TEST_SECRETOBOOT_NEXT_BOOT'){throw 'BOOTNEXT_CONSENT_DENIED'};$before=[byte[]]$canonical.BootOrder;$bootNextAssigned=$false;try{[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::SetInstalledBootNextAndVerify($entry,$entryName,$loadOption,$targetPartitionGuid);$bootNextAssigned=$true;$after=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootOrder');if(-not([Convert]::ToBase64String($after)-ceq[Convert]::ToBase64String($before))){throw 'PERMANENT_BOOT_ORDER_CHANGED_DURING_TEST'};$stage='TestNextStateCommit';$tx=[pscustomobject][ordered]@{SchemaVersion='v9-deployment-transaction-1';Revision=$revision;Stage='BootNextVerified';TargetEspPartitionGuid=[string]$targetPartitionGuid;FirmwareEntryNumber=[int]$entry;RollbackRequired=$false;BootNextVerified=$true;TestInstalledIdentityDigest=[string]$canonical.InstalledIdentityDigest;TestFirmwareEntryNumber=[int]$entry;TestPartitionGuid=[string]$targetPartitionGuid;TestRefindSha256=[string]$manifest.InstalledFiles.'refind_x64.efi';TestInstalledRevision=[string]$manifest.Revision;ThemeRevision='FinalRelease.1';ThemeDeployment='MATCH';CompletedUtc=[DateTime]::UtcNow.ToString('o')};Write-State $tx $statePath;$result=[pscustomobject]@{Reason='TEST_BOOT_READY_VERIFIED';Message='The next restart will boot the verified FinalRelease.1 SecretoBoot runtime once. The persistent default boot order was not changed.'}}catch{if($bootNextAssigned){try{[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ClearOwnedBootNext($entry);$restored=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootOrder');if(-not([Convert]::ToBase64String($restored)-ceq[Convert]::ToBase64String($before))){throw 'TEST_BOOT_ROLLBACK_ORDER_MISMATCH'};$script:rollbackStatus='Completed'}catch{$script:rollbackStatus='Failed';throw 'TEST_BOOT_ROLLBACK_FAILED'}};throw}}
                    'MakeDefault' {
                        $stage='PersistentDefaultConsent';if($ConsentPhrase-cne'MAKE_SECRETOBOOT_DEFAULT'){throw 'BOOTORDER_CONSENT_DENIED'}
                        $stage='PersistentDefaultCurrentTestVerification';$null=Test-CurrentOneTimeVerification $canonical
                        $stage='PersistentDefaultFreshStateReload';$freshManifest=Read-Ownership;$freshIdentity=Get-InstalledFirmwareIdentity $freshManifest;$freshCanonical=Get-CanonicalInstalledState $freshManifest $freshIdentity $access $owned $validatedDefaultCore $false;if([string]$freshCanonical.InstalledIdentityDigest-cne[string]$canonical.InstalledIdentityDigest){throw 'STALE_REPAIRED_FIRMWARE_IDENTITY'};$null=Test-CurrentOneTimeVerification $freshCanonical
                        $manifest=$freshManifest;$identity=$freshIdentity;$canonical=$freshCanonical;$entry=[uint16]$identity.EntryNumber;$entryName=[string]$identity.EntryName;$loadOption=[byte[]]$identity.LoadOption;$targetPartitionGuid=[guid]$identity.PartitionGuid;$before=[byte[]]$canonical.BootOrder;$beforeTargets=$canonical.BootTargets;$windowsEvidence=$canonical.WindowsRecovery
                        $rollbackContext=Get-PersistentDefaultRollbackContext $canonical $owned;$oldEfiManifest=[string]$rollbackContext.EfiManifestText;$oldStateManifest=[string]$rollbackContext.StateManifestText;$oldSnapshot=$rollbackContext.SnapshotText
                        $snapshotWritten=$false;try{$snapshot=New-PersistentDefaultSnapshot $canonical;$snapshotWritten=$true}catch{throw}
                        $defaultWritten=$false;try{
                            $stage='PersistentBootOrderWrite';try{[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::MakeDefault($entry)}finally{$nativePersistentDiagnostic=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::LastPersistentDefaultDiagnostic;if(-not[string]::IsNullOrWhiteSpace($nativePersistentDiagnostic)){$script:resolverDiagnostic=$nativePersistentDiagnostic}};$defaultWritten=$true
                            $stage='PersistentBootOrderReadback';[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::VerifyInstalledPersistentDefault($entry,$entryName,$loadOption,$targetPartitionGuid,$before)
                            $stage='PersistentDefaultPostWriteTargetVerification';$afterTargets=Get-CurrentBootTargetSnapshot $validatedDefaultCore $access;Test-BootTargetSnapshot $beforeTargets $afterTargets;$null=Get-WindowsFirmwareEvidence $validatedDefaultCore ([SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootOrder'))
                            $stage='PersistentDefaultStateCommit';$manifest.PreviousBootOrderBase64=[Convert]::ToBase64String($before);$manifest.BootOrderChangedByMakeDefault=$true;$manifest|Add-Member -NotePropertyName PersistentDefaultVerifiedUtc -NotePropertyValue ([DateTime]::UtcNow.ToString('o')) -Force;Write-State $manifest (Join-Path $owned 'ownership-manifest.json');Write-State $manifest $ownershipStatePath
                            $stage='PersistentDefaultFinalVerification';$verified=Read-Ownership;if($verified.BootOrderChangedByMakeDefault-ne$true-or[string]$verified.PreviousBootOrderBase64-cne[Convert]::ToBase64String($before)){throw 'PERSISTENT_DEFAULT_STATE_READBACK_DENIED'};[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::VerifyInstalledPersistentDefault($entry,$entryName,$loadOption,$targetPartitionGuid,$before);$finalCanonical=Get-CanonicalInstalledState $verified (Get-InstalledFirmwareIdentity $verified) $access $owned $validatedDefaultCore $false;Test-BootTargetSnapshot $beforeTargets $finalCanonical.BootTargets;if([BitConverter]::ToUInt16($finalCanonical.BootOrder,0)-ne$entry){throw 'PERSISTENT_DEFAULT_READBACK_MISMATCH'}
                        }catch{$original=Get-SafeReason $_;if($original-ceq'UNEXPECTED_OPERATION_FAILURE'){$original='PERSISTENT_DEFAULT_POSTWRITE_RUNTIME_FAILED'};try{if($defaultWritten){$stage='PersistentDefaultRollback';[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::RestoreExactOrder($before)};[IO.File]::WriteAllText((Join-Path $owned 'ownership-manifest.json'),$oldEfiManifest,[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText($ownershipStatePath,$oldStateManifest,[Text.UTF8Encoding]::new($false));if($null-ne$oldSnapshot){[IO.File]::WriteAllText($persistentSnapshotPath,$oldSnapshot,[Text.UTF8Encoding]::new($false))}elseif($snapshotWritten-and[IO.File]::Exists($persistentSnapshotPath)){[IO.File]::Delete($persistentSnapshotPath)};if($defaultWritten-or$snapshotWritten){$script:rollbackStatus='Completed'}}catch{$script:rollbackStatus='Failed';throw 'PERSISTENT_DEFAULT_ROLLBACK_FAILED'};throw $original}
                        $result=[pscustomobject]@{Reason='SECRETOBOOT_PERSISTENT_DEFAULT_VERIFIED';Message='SecretoBoot is now the verified persistent default boot manager. It will appear on normal startups. Windows Boot Manager remains installed and can be restored as default.'}
                    }
                    'EnableWindowsFirstCompatibility' {
                        $stage='WindowsFirstCompatibilityConsent';if($ConsentPhrase-cne'ENABLE_WINDOWS_FIRST_FIRMWARE_COMPATIBILITY'){throw 'WINDOWS_FIRST_COMPATIBILITY_CONSENT_DENIED'}
                        $stage='WindowsFirstCompatibilityPreflight';$null=Test-WindowsFirstCompatibilityPreflight $canonical $manifest $validatedDefaultCore
                        $originalManifestJson=Get-StateText $manifest;$pathChanged=$false
                        try{
                            $stage='WindowsFirstCompatibilityBcdPathWrite';$originalPath=Get-NativeWindowsBootManagerPath;if([string]$originalPath-ine'\EFI\Microsoft\Boot\bootmgfw.efi'){throw 'NATIVE_WINDOWS_BOOT_PATH_UNEXPECTED'};$null=Set-NativeWindowsBootManagerPath '\EFI\SecretoBoot\refind_x64.efi';$pathChanged=$true
                            $stage='WindowsFirstCompatibilityBcdPathReadback';$compatibilityPath=Get-NativeWindowsBootManagerPath;if([string]$compatibilityPath-ine'\EFI\SecretoBoot\refind_x64.efi'){throw 'WINDOWS_BOOTMGR_PATH_READBACK_MISMATCH'}
                            $stage='WindowsFirstCompatibilityStateCommit';$manifest.Revision=$revision;$manifest.BootOrderChangedByMakeDefault=$false;$manifest|Add-Member -NotePropertyName FirmwareRestoredWindowsFirstObserved -NotePropertyValue $true -Force;$manifest|Add-Member -NotePropertyName WindowsFirstCompatibilityMode -NotePropertyValue $true -Force;$manifest|Add-Member -NotePropertyName OriginalWindowsBootManagerPath -NotePropertyValue '\EFI\Microsoft\Boot\bootmgfw.efi' -Force;$manifest|Add-Member -NotePropertyName WindowsFirstCompatibilityEnabledUtc -NotePropertyValue ([DateTime]::UtcNow.ToString('o')) -Force;Write-State $manifest (Join-Path $owned 'ownership-manifest.json');Write-State $manifest $ownershipStatePath
                            $stage='WindowsFirstCompatibilityStateReadback';$verified=Read-Ownership;if($verified.WindowsFirstCompatibilityMode-ne$true-or[string]$verified.OriginalWindowsBootManagerPath-ine'\EFI\Microsoft\Boot\bootmgfw.efi'){throw 'WINDOWS_FIRST_COMPATIBILITY_STATE_READBACK_DENIED'}
                        }catch{$reason=Get-SafeReason $_;try{if($pathChanged){$null=Set-NativeWindowsBootManagerPath '\EFI\Microsoft\Boot\bootmgfw.efi'};[IO.File]::WriteAllText((Join-Path $owned 'ownership-manifest.json'),$originalManifestJson,[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText($ownershipStatePath,$originalManifestJson,[Text.UTF8Encoding]::new($false));if($pathChanged){$script:rollbackStatus='Completed'}}catch{$script:rollbackStatus='Failed';throw 'WINDOWS_FIRST_COMPATIBILITY_ROLLBACK_FAILED'};throw $reason}
                        $result=[pscustomobject]@{Reason='WINDOWS_FIRST_FIRMWARE_COMPATIBILITY_VERIFIED';Message='Windows-First Firmware Compatibility Mode is enabled. The Windows firmware entry now launches the verified SecretoBoot EFI loader. Microsoft bootmgfw.efi was not modified. Windows remains the default selection inside SecretoBoot.'}
                    }
                    'RestoreNativeWindowsBoot' {
                        $stage='NativeWindowsRestoreConsent';if($ConsentPhrase-cne'RESTORE_NATIVE_WINDOWS_BOOT'){throw 'NATIVE_WINDOWS_RESTORE_CONSENT_DENIED'};if($manifest.PSObject.Properties.Name-notcontains'WindowsFirstCompatibilityMode'-or$manifest.WindowsFirstCompatibilityMode-ne$true-or[string]$manifest.OriginalWindowsBootManagerPath-ine'\EFI\Microsoft\Boot\bootmgfw.efi'){throw 'WINDOWS_FIRST_COMPATIBILITY_STATE_INVALID'}
                        $oldEfiManifest=Get-Content (Join-Path $owned 'ownership-manifest.json') -Raw;$oldStateManifest=Get-Content $ownershipStatePath -Raw;$restored=$false
                        try{$stage='NativeWindowsBcdPathRestore';if([string]$manifest.OriginalWindowsBootManagerPath-ine'\EFI\Microsoft\Boot\bootmgfw.efi'){throw 'RECORDED_NATIVE_WINDOWS_BOOT_PATH_DENIED'};$null=Set-NativeWindowsBootManagerPath '\EFI\Microsoft\Boot\bootmgfw.efi';$restored=$true;$stage='NativeWindowsStateCommit';$manifest.WindowsFirstCompatibilityMode=$false;$manifest|Add-Member -NotePropertyName NativeWindowsBootRestoredUtc -NotePropertyValue ([DateTime]::UtcNow.ToString('o')) -Force;Write-State $manifest (Join-Path $owned 'ownership-manifest.json');Write-State $manifest $ownershipStatePath;if((Get-NativeWindowsBootManagerPath)-ine'\EFI\Microsoft\Boot\bootmgfw.efi'){throw 'NATIVE_WINDOWS_BOOT_RESTORE_READBACK_DENIED'}
                        }catch{$reason=Get-SafeReason $_;try{if($restored){$null=Set-NativeWindowsBootManagerPath '\EFI\SecretoBoot\refind_x64.efi'};[IO.File]::WriteAllText((Join-Path $owned 'ownership-manifest.json'),$oldEfiManifest,[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText($ownershipStatePath,$oldStateManifest,[Text.UTF8Encoding]::new($false));if($restored){$script:rollbackStatus='Completed'}}catch{$script:rollbackStatus='Failed';throw 'NATIVE_WINDOWS_RESTORE_ROLLBACK_FAILED'};throw $reason}
                        $result=[pscustomobject]@{Reason='NATIVE_WINDOWS_BOOT_RESTORED_VERIFIED';Message='The exact native Windows Boot Manager path is restored. Microsoft boot files were not replaced or modified.'}
                    }
                    'RestorePreviousDefault' {$stage='RestoreBootOrder';if($ConsentPhrase-cne'RESTORE_PREVIOUS_DEFAULT'){throw 'RESTORE_ORDER_CONSENT_DENIED'};$snapshot=Read-CurrentPersistentSnapshot $canonical;$previous=[Convert]::FromBase64String([string]$snapshot.OriginalBootOrderBase64);$windowsEntry=Get-WindowsFirmwareEvidence $validatedDefaultCore $previous;if([BitConverter]::ToUInt16($previous,0)-ne[uint16]$windowsEntry.EntryNumber-or[uint16]$windowsEntry.EntryNumber-ne[uint16]$snapshot.WindowsEntryNumber){throw 'RECORDED_WINDOWS_DEFAULT_IDENTITY_DENIED'};[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::RestorePreviousOrder($entry,$previous);$actual=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable('BootOrder');if(-not([Convert]::ToBase64String($actual)-ceq[Convert]::ToBase64String($previous))){throw 'WINDOWS_DEFAULT_RESTORE_READBACK_DENIED'};$null=Get-WindowsFirmwareEvidence $validatedDefaultCore $actual;$manifest.BootOrderChangedByMakeDefault=$false;Write-State $manifest (Join-Path $owned 'ownership-manifest.json');Write-State $manifest $ownershipStatePath;$result=[pscustomobject]@{Reason='WINDOWS_DEFAULT_RESTORED_VERIFIED';Message='Windows Boot Manager is restored as the verified persistent default. SecretoBoot remains installed.'}}
                    {$_-in@('Rollback','Uninstall')} {$stage='OwnedStateRemoval';if($ConsentPhrase-notin@('ROLLBACK_SECRETOBOOT','UNINSTALL_SECRETOBOOT_EXPERIMENTAL')){throw 'REMOVAL_CONSENT_DENIED'};if($manifest.PSObject.Properties.Name-contains'WindowsFirstCompatibilityMode'-and$manifest.WindowsFirstCompatibilityMode-eq$true){$stage='OwnedStateNativeWindowsRestore';if([string]$manifest.OriginalWindowsBootManagerPath-ine'\EFI\Microsoft\Boot\bootmgfw.efi'){throw 'RECORDED_NATIVE_WINDOWS_BOOT_PATH_DENIED'};$null=Set-NativeWindowsBootManagerPath '\EFI\Microsoft\Boot\bootmgfw.efi'};$stage='OwnedStateRemoval';$equivalent=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::SelectEquivalentOwnedEntry($targetPartitionGuid,[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadBootInventory());$removedFirmware=$false;if($null-ne$equivalent){$currentLoad=[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::ReadVariable([string]$equivalent.FirmwareIdentifier);[SecretoBoot.V9.WindowsFirmware.FirmwareAdapter]::RemoveOwnedEntry([uint16]$equivalent.EntryNumber,[byte[]]$currentLoad);$removedFirmware=$true};Remove-OwnedTree $manifest $owned;if([IO.File]::Exists($ownershipStatePath)){[IO.File]::Delete($ownershipStatePath)};if([IO.File]::Exists($statePath)){[IO.File]::Delete($statePath)};if([IO.File]::Exists($persistentSnapshotPath)){[IO.File]::Delete($persistentSnapshotPath)};$result=[pscustomobject]@{Reason=if($removedFirmware){'OWNED_STATE_REMOVED'}else{'OWNED_STATE_REMOVED_FIRMWARE_ALREADY_ABSENT'};Message='Only manifest-owned SecretoBoot state was removed. Native Windows boot flow is restored.'}}
                }
            }finally{if($null-ne$access){Close-PartitionAccess $access}}
        }
    }
    Write-OperationResult 'PASS' $stage $result.Reason $result.Message;exit 0
}catch{$reason=Get-SafeReason $_;try{Write-OperationResult 'FAIL' $stage $reason 'The operation failed closed. No unverified success was reported.'}catch{};exit 1}
