[CmdletBinding()]param([Parameter(Mandatory)][switch]$ApproveCanonicalEvidence,[Parameter(Mandatory)][ValidateSet('I_APPROVE_SECRETOBOOT_BOUNDED_READ_ONLY_CANONICAL_EVIDENCE')][string]$ConsentPhrase,[Parameter(Mandatory)][ValidatePattern('^[0-9a-f]{64}$')][string]$ExpectedManifestDigest)
$ErrorActionPreference='Stop';$backend=Join-Path $PSScriptRoot 'discovery';$canonical=Join-Path $PSScriptRoot 'canonical-runtime'
$integrityPath=Join-Path $PSScriptRoot 'canonical-runtime-integrity.json';$integrity=Get-Content $integrityPath -Raw|ConvertFrom-Json;if($integrity.ManifestVersion-cne'v9-canonical-runtime-integrity-1'){throw 'CANONICAL_RUNTIME_INTEGRITY_DENIED'};$expected=@($integrity.ExpectedFileList);if($expected.Count-ne@($integrity.Files.PSObject.Properties).Count){throw 'CANONICAL_RUNTIME_INTEGRITY_DENIED'};foreach($relative in $expected){if([string]$relative-notmatch'^[A-Za-z0-9._/-]+$'-or[string]$relative-match'(^|/)\.\.(/|$)'){throw 'CANONICAL_RUNTIME_INTEGRITY_DENIED'};$path=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot ([string]$relative)));if(-not$path.StartsWith([IO.Path]::GetFullPath($PSScriptRoot)+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)-or-not[IO.File]::Exists($path)){throw 'CANONICAL_RUNTIME_INTEGRITY_DENIED'};$hash=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([IO.File]::ReadAllBytes($path))).ToLowerInvariant();if($hash-cne[string]$integrity.Files.$relative){throw 'CANONICAL_RUNTIME_INTEGRITY_DENIED'}}
Import-Module (Join-Path $backend 'SecretoBoot.WindowsLevel1.Manifest.psm1') -Force;Import-Module (Join-Path $backend 'SecretoBoot.WindowsLevel1.ProductionTransport.psm1') -Force;Import-Module (Join-Path $backend 'SecretoBoot.WindowsLevel1.ReportValidation.psm1') -Force;Import-Module (Join-Path $backend 'SecretoBoot.AndroidAccessible.Manifest.psm1') -Force;Import-Module (Join-Path $backend 'SecretoBoot.AndroidAccessible.Transport.psm1') -Force
Import-Module (Join-Path $canonical 'SecretoBoot.MultiOsMvpEfi.Manifest.psm1') -Force;Import-Module (Join-Path $canonical 'SecretoBoot.MultiOsMvpEfi.Transport.psm1') -Force;Import-Module (Join-Path $canonical 'SecretoBoot.CanonicalEvidenceCollector.psm1') -Force;Import-Module (Join-Path $canonical 'SecretoBoot.AndroidInstallationRelationship.psm1') -Force;Import-Module (Join-Path $canonical 'SecretoBoot.DiscoveryDiagnostics.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'SecretoBoot.RefindSetupPreview.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'SecretoBoot.EndToEnd.psm1') -Force
$runtime=Join-Path $backend 'runtime/src';Import-Module (Join-Path $runtime 'Providers/WindowsLevel1/SecretoBoot.WindowsLevel1.Parsers.psm1') -Force;Import-Module (Join-Path $runtime 'Providers/WindowsLevel1/SecretoBoot.WindowsLevel1.Privacy.psm1') -Force;Import-Module (Join-Path $canonical 'Providers/WindowsAndroidEvidence/SecretoBoot.WindowsAndroidEvidence.psm1') -Force;Import-Module (Join-Path $canonical 'Providers/WindowsEfiEvidence/SecretoBoot.WindowsEfiEvidence.psm1') -Force;Import-Module (Join-Path $runtime 'Discovery/SecretoBoot.MultiOsMvp.psm1') -Force;Import-Module (Join-Path $runtime 'Discovery/SecretoBoot.MultiOsAndroidCorrelation.psm1') -Force
$pre=& (Join-Path $backend 'Invoke-Preflight.ps1') -FeatureGateState ([bool]$ApproveCanonicalEvidence);if(-not$pre.Ready-or$ConsentPhrase-cne'I_APPROVE_SECRETOBOOT_BOUNDED_READ_ONLY_CANONICAL_EVIDENCE'){throw 'CANONICAL_PREFLIGHT_DENIED'}
$level1=New-SbLevel1ExecutionManifest -FeatureGateState $true -ExplicitConsent $true -PlatformCheck Passed;if(-not(Test-SbLevel1ExecutionManifest $level1).Allowed){throw 'CANONICAL_LEVEL1_MANIFEST_DENIED'}
$androidManifest=New-SbAndroidAccessibleManifest -Level1ManifestDigest (Get-SbLevel1ManifestDigest $level1) -FeatureGateState $true -ExplicitConsent $true -NonElevated $true -PlatformCheck Passed;if(-not(Test-SbAndroidAccessibleManifest $androidManifest).Allowed-or(Get-SbAndroidAccessibleManifestDigest $androidManifest)-ne$ExpectedManifestDigest){throw 'CANONICAL_REVIEWED_MANIFEST_DENIED'}
$efiManifest=New-SbMultiOsMvpEfiManifest -Level1ManifestDigest (Get-SbLevel1ManifestDigest $level1) -FeatureGateState $true -ExplicitConsent $true -NonElevated $true -PlatformCheck Passed;if(-not(Test-SbMultiOsMvpEfiManifest $efiManifest).Allowed){throw 'CANONICAL_EFI_MANIFEST_DENIED'}
$results=@{};foreach($id in @('platform.runtime','platform.environment','windows.os.cim','storage.disks','storage.partitions','storage.volumes')){$results[$id]=Invoke-SbWindowsLevel1ProductionTransport $id $level1;if($results[$id].Status-ne'Success'){throw "CANONICAL_LEVEL1_OPERATION_FAILED: $id"}}
$payload=ConvertTo-SbProductionParserPayload $results['platform.runtime'].Data $results['platform.environment'].Data $results['windows.os.cim'].Data $results['storage.disks'].Data $results['storage.partitions'].Data $results['storage.volumes'].Data;$parsed=ConvertFrom-SbWindowsLevel1Payload $payload;if($parsed.Status-eq'Rejected'){throw 'CANONICAL_LEVEL1_PARSE_DENIED'};$privacy=New-SbLevel1PrivacyContext;$safe=ConvertTo-SbLevel1SafeReport $parsed.Inventory $privacy;if(-not(Test-SbWindowsLevel1SafeReport $safe).Valid){throw 'CANONICAL_SAFE_REPORT_DENIED'};$mvp=ConvertTo-SbMultiOsMvpReport $safe -WindowsCimEvidencePresent ($results['windows.os.cim'].Status-eq'Success'-and@($results['windows.os.cim'].Data).Count-eq1)
$access=@(Invoke-SbAndroidAccessPathInventory $androidManifest);$inspections=[Collections.Generic.List[object]]::new();$eligible=0
foreach($record in $access){$partitionId=Protect-SbLevel1ReportValue $privacy 'partition' ([string]$record.PartitionGuid);$candidate=@($mvp.DetectedSystems|Where-Object{$_.CandidateKind-eq'PartitionCandidate'-and$_.PartitionId-ceq$partitionId}|Select-Object -First 1);if(-not$candidate.Count-or$candidate[0].FilesystemAccessibility-cne'AccessibleButNotReadByMvp'-or$candidate[0].Filesystem-notin@('FAT32','exFAT','NTFS')){continue};$eligible++;if($eligible-gt[int]$androidManifest.MaximumInspectableVolumes){throw 'CANONICAL_ANDROID_RESOURCE_LIMIT'};$volumes=@($record.VolumeGuids|Sort-Object -Unique);if($volumes.Count-ne1){$inspections.Add([pscustomobject]@{Status='Denied';ReasonCode=if($volumes.Count){'ANDROID_EVIDENCE_VOLUME_AMBIGUOUS'}else{'ANDROID_EVIDENCE_VOLUME_PATH_UNAVAILABLE'};DiagnosticReasonCode='ACCESS_PATH_UNAVAILABLE';PartitionId=$partitionId;Evidence=@();PathDiagnostics=@();NativeOpenOperations=0;BoundedReadOperations=0;BytesRead=0});continue};$inspections.Add((Invoke-SbWindowsAndroidEvidenceInspection -VolumeGuid ([guid]$volumes[0]) -PartitionId $partitionId -Filesystem ([string]$candidate[0].Filesystem) -EnableAndroidEvidence -GrantExplicitConsent))}
$report=ConvertTo-SbMultiOsAndroidEvidenceReport -MvpReport $mvp -InspectionResults $inspections.ToArray()
$canonicalEvidence=[Collections.Generic.List[object]]::new();$canonicalCorrelations=[Collections.Generic.List[object]]::new();$denied=[Collections.Generic.List[object]]::new();$efiInspectionRecords=[Collections.Generic.List[object]]::new();$opens=0;$reads=0;$bytes=0;$espCount=0
$efiAccess=@(Invoke-SbEfiAccessPathInventory $efiManifest);if($efiAccess.Count-gt[int]$efiManifest.MaximumEspCandidates){throw 'CANONICAL_ESP_RESOURCE_LIMIT'}
foreach($record in $efiAccess){$token=Protect-SbLevel1ReportValue $privacy 'partition' ([string]$record.PartitionGuid);if(-not@($mvp.BootEvidenceCandidates|Where-Object{[string]$_.PartitionId-ceq$token}).Count){continue};$espCount++;$volumes=@($record.VolumeGuids|Sort-Object -Unique);if($volumes.Count-ne1){$reason=if($volumes.Count){'AMBIGUOUS_ACCESS_PATH'}else{'ACCESS_UNAVAILABLE'};$denied.Add([pscustomobject]@{ReasonCode=$reason});$efiInspectionRecords.Add([pscustomobject]@{Status='Denied';ReasonCode=$reason;Token=$token;VolumeGuidCount=$volumes.Count;PathDiagnostics=@()});continue};$inspection=Invoke-SbWindowsEfiEvidenceInspection -VolumeGuid ([guid]$volumes[0]) -EspToken $token -EnableEfiEvidence -GrantExplicitConsent;$efiInspectionRecords.Add([pscustomobject]@{Status=[string]$inspection.Status;ReasonCode=[string]$inspection.ReasonCode;Token=$token;VolumeGuidCount=1;PathDiagnostics=@($inspection.PathDiagnostics)});$opens+=[int]$inspection.NativeOpenOperations;$reads+=[int]$inspection.BoundedReadOperations;$bytes+=[long]$inspection.BytesRead;if($inspection.Status-cne'Complete'){$denied.Add([pscustomobject]@{ReasonCode=[string]$inspection.ReasonCode});continue};$rawPartition=@($parsed.Inventory.Partitions|Where-Object{[string]$_.PartitionGuid-ceq[string]$record.PartitionGuid}|Select-Object -First 1);if($rawPartition.Count-ne1){$denied.Add([pscustomobject]@{ReasonCode='CANONICAL_ESP_IDENTITY_AMBIGUOUS'});continue};foreach($artifact in @($inspection.Evidence|Where-Object{[string]$_.Kind-ceq'EfiLoader'})){$item=ConvertTo-SbCanonicalEfiEvidence $artifact ([guid]$record.PartitionGuid) ([guid]$rawPartition[0].DiskGuid);$canonicalEvidence.Add($item);if('microsoft-vendor-path'-in$item.Signals){$canonicalCorrelations.Add([pscustomobject]@{EvidenceId=$item.EvidenceId;SystemId='mvp:host:windows';Relationship='Corroborates';RootPartitionResolved=$false})}}}
$summary=New-SbCanonicalEvidenceCollectionSummary $canonicalEvidence.ToArray() $denied.ToArray() $espCount $opens $reads $bytes
$partitionInventory=@($parsed.Inventory.Partitions|ForEach-Object{[pscustomobject]@{OpaquePartitionId=Protect-SbLevel1ReportValue $privacy 'partition' ([string]$_.PartitionGuid);RawPartitionId=[string]$_.PartitionGuid;RawDiskId=[string]$_.DiskGuid;Filesystem=[string]$_.Filesystem;DisplayLabel=[string]$_.DisplayLabel}})
$relationships=Resolve-SbAndroidInstallationRelationships -DetectedSystems $report.DetectedSystems -InspectionResults $inspections.ToArray() -PartitionInventory $partitionInventory
$allEvidence=@($report.Evidence)+@($summary.Evidence)+@($relationships.Evidence);$allCorrelations=@($report.Correlations)+@($canonicalCorrelations)+@($relationships.Correlations)
$approvedAndroidPaths=@([SecretoBoot.V9.WindowsAndroidEvidence.AndroidEvidenceAdapter]::ApprovedRelativePaths());$diagnostics=New-SbDiscoveryDiagnostics $relationships.DetectedSystems $report.Evidence $inspections.ToArray() $approvedAndroidPaths @($mvp.BootEvidenceCandidates).Count $efiAccess $efiInspectionRecords.ToArray() (@($summary.Evidence)+@($relationships.Evidence)) $relationships.Relationships
$assetManifest=[pscustomobject]@{};$blissChainloadCandidates=@()
try {
    $assetManifest=Get-Content (Join-Path $PSScriptRoot 'refind-assets.json') -Raw|ConvertFrom-Json
    $blissChainloadCandidates=Resolve-SbBlissEfiChainloadCandidates -InspectionResults $inspections.ToArray() -PartitionInventory $partitionInventory
    $windowsResolutionCandidates=@($efiInspectionRecords|ForEach-Object{[pscustomobject]@{CandidateId=$_.Token;Filesystem='FAT32';UsableVolumeGuidAccessPath=([int]$_.VolumeGuidCount-eq1);VolumeGuidCount=[int]$_.VolumeGuidCount;PathDiagnostics=@($_.PathDiagnostics);FailureReason=if([string]$_.ReasonCode-ceq'EFI_EVIDENCE_OK'){'NOT_FOUND'}elseif([string]$_.ReasonCode-ceq'EFI_EVIDENCE_CONTAINMENT_DENIED'){'CONTAINMENT_DENIED'}else{'OPEN_FAILED'}}})
    $blissResolutionCandidates=@($partitionInventory|Where-Object{[string]$_.Filesystem-ceq'FAT32'}|ForEach-Object{$partition=$_;$accessRecord=@($access|Where-Object{[string]$_.PartitionGuid-ceq[string]$partition.RawPartitionId}|Select-Object -First 1);$volumeCount=if($accessRecord.Count){@($accessRecord[0].VolumeGuids|Sort-Object -Unique).Count}else{0};$inspectionRecord=@($inspections|Where-Object{[string]$_.PartitionId-ceq[string]$partition.OpaquePartitionId}|Select-Object -First 1);[pscustomobject]@{CandidateId=$partition.OpaquePartitionId;UsableVolumeGuidAccessPath=($volumeCount-eq1);VolumeGuidCount=$volumeCount;PathDiagnostics=if($inspectionRecord.Count){@($inspectionRecord[0].PathDiagnostics)}else{@()}}})
    $resolutionDiagnostics=New-SbRefindResolutionDiagnostics -WindowsCandidates $windowsResolutionCandidates -BlissCandidates $blissResolutionCandidates -BlissCanonicalBootChains @($blissChainloadCandidates)
    $setupPreview=New-SbRefindSetupPreview -RawPartitions @($parsed.Inventory.Partitions) -CanonicalEfiEvidence @($summary.Evidence) -AndroidCanonicalBootChains @($blissChainloadCandidates) -ResolutionDiagnostics $resolutionDiagnostics -AssetManifest $assetManifest
}
catch {
    $setupReason=if([string]$_.Exception.Message -in @('REFIND_SETUP_ASSET_MANIFEST_DENIED','REFIND_SETUP_RESOURCE_CAP_EXCEEDED','REFIND_SETUP_BLISS_RESOURCE_CAP_EXCEEDED')){[string]$_.Exception.Message}else{'REFIND_SETUP_PREVIEW_FAILED'}
    $setupDependencies='RefindSetupPreview='+$(if(Test-Path (Join-Path $PSScriptRoot 'SecretoBoot.RefindSetupPreview.psm1') -PathType Leaf){'Present'}else{'Missing'})+'; RefindAssets='+$(if(Test-Path (Join-Path $PSScriptRoot 'refind-assets.json') -PathType Leaf){'Present'}else{'Missing'})
    $setupPreview=New-SbUnavailableRefindSetupPreview -ReasonCode $setupReason -ExceptionType $_.Exception.GetType().FullName -SafeMessage $_.Exception.Message -DependencyAvailability $setupDependencies
}
$endToEndPlan=New-SbEndToEndExperimentalPlan -RefindSetupPreview $setupPreview -CanonicalEfiEvidence @($summary.Evidence) -AndroidCanonicalBootChains @($blissChainloadCandidates) -RawPartitions @($parsed.Inventory.Partitions) -AssetManifest $assetManifest
[pscustomobject][ordered]@{SchemaVersion='v9canonicalevidencecollection1';Status=if($summary.Denied.Count){'PARTIAL'}else{$report.Status};DynamicCollection=$true;DetectedSystems=$relationships.DetectedSystems;Evidence=$allEvidence;Correlations=$allCorrelations;DeniedInspections=$report.DeniedInspections;CanonicalEvidence=@($summary.Evidence)+@($relationships.Evidence);CanonicalEvidenceDenied=$summary.Denied;AndroidCanonicalBootChains=$relationships.CanonicalBootChains;AndroidInstallationRelationships=$relationships.Relationships;DiscoveryDiagnostics=$diagnostics;DiagnosticReport=Format-SbDiscoveryDiagnostics $diagnostics;RefindSetupPreview=$setupPreview;RefindSetupReport=Format-SbRefindSetupPreview $setupPreview;EndToEndPlan=$endToEndPlan;Counts=[pscustomobject]@{DetectedSystems=$report.Counts.DetectedSystems;Evidence=$allEvidence.Count;Correlations=$allCorrelations.Count;CanonicalEvidence=@($summary.Evidence).Count+@($relationships.Evidence).Count};SafetyCounters=$report.SafetyCounters;CanonicalReadCounters=$summary.Counters;RelationshipSafetyCounters=$relationships.SafetyCounters}
