[CmdletBinding()]param([Parameter(Mandatory)][switch]$ApproveAndroidAccessibleEvidence,[Parameter(Mandatory)][ValidateSet('I_APPROVE_SECRETOBOOT_READ_ONLY_ANDROID_VOLUME_EVIDENCE')][string]$ConsentPhrase,[Parameter(Mandatory)][ValidatePattern('^[0-9a-f]{64}$')][string]$ExpectedManifestDigest)
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'SecretoBoot.WindowsLevel1.Manifest.psm1') -Force;Import-Module (Join-Path $PSScriptRoot 'SecretoBoot.WindowsLevel1.ProductionTransport.psm1') -Force;Import-Module (Join-Path $PSScriptRoot 'SecretoBoot.WindowsLevel1.ReportValidation.psm1') -Force;Import-Module (Join-Path $PSScriptRoot 'SecretoBoot.AndroidAccessible.Manifest.psm1') -Force;Import-Module (Join-Path $PSScriptRoot 'SecretoBoot.AndroidAccessible.Transport.psm1') -Force
$runtime=Join-Path $PSScriptRoot 'runtime/src';Import-Module (Join-Path $runtime 'Providers/WindowsLevel1/SecretoBoot.WindowsLevel1.Parsers.psm1') -Force;Import-Module (Join-Path $runtime 'Providers/WindowsLevel1/SecretoBoot.WindowsLevel1.Privacy.psm1') -Force;Import-Module (Join-Path $runtime 'Providers/WindowsAndroidEvidence/SecretoBoot.WindowsAndroidEvidence.psm1') -Force;Import-Module (Join-Path $runtime 'Discovery/SecretoBoot.MultiOsMvp.psm1') -Force;Import-Module (Join-Path $runtime 'Discovery/SecretoBoot.MultiOsAndroidCorrelation.psm1') -Force
$pre=& (Join-Path $PSScriptRoot 'Invoke-Preflight.ps1') -FeatureGateState ([bool]$ApproveAndroidAccessibleEvidence);if(-not$pre.Ready){throw 'ANDROID_PREFLIGHT_DENIED'}
$level1=New-SbLevel1ExecutionManifest -FeatureGateState $true -ExplicitConsent ($ConsentPhrase-eq'I_APPROVE_SECRETOBOOT_READ_ONLY_ANDROID_VOLUME_EVIDENCE') -PlatformCheck Passed;if(-not(Test-SbLevel1ExecutionManifest $level1).Allowed){throw 'ANDROID_LEVEL1_MANIFEST_DENIED'}
$manifest=New-SbAndroidAccessibleManifest -Level1ManifestDigest (Get-SbLevel1ManifestDigest $level1) -FeatureGateState $true -ExplicitConsent $true -NonElevated $true -PlatformCheck Passed;$gate=Test-SbAndroidAccessibleManifest $manifest;if(-not$gate.Allowed-or(Get-SbAndroidAccessibleManifestDigest $manifest)-ne$ExpectedManifestDigest){throw 'ANDROID_REVIEWED_MANIFEST_DENIED'}
$results=@{};foreach($id in @('platform.runtime','platform.environment','windows.os.cim','storage.disks','storage.partitions','storage.volumes')){$results[$id]=Invoke-SbWindowsLevel1ProductionTransport $id $level1;if($results[$id].Status-ne'Success'){throw "ANDROID_LEVEL1_OPERATION_FAILED: $id"}}
$payload=ConvertTo-SbProductionParserPayload $results['platform.runtime'].Data $results['platform.environment'].Data $results['windows.os.cim'].Data $results['storage.disks'].Data $results['storage.partitions'].Data $results['storage.volumes'].Data;$parsed=ConvertFrom-SbWindowsLevel1Payload $payload;if($parsed.Status-eq'Rejected'){throw 'ANDROID_LEVEL1_PARSE_DENIED'};$privacy=New-SbLevel1PrivacyContext;$safe=ConvertTo-SbLevel1SafeReport $parsed.Inventory $privacy;if(-not(Test-SbWindowsLevel1SafeReport $safe).Valid){throw 'ANDROID_SAFE_REPORT_DENIED'};$mvp=ConvertTo-SbMultiOsMvpReport $safe -WindowsCimEvidencePresent ($results['windows.os.cim'].Status-eq'Success'-and@($results['windows.os.cim'].Data).Count-eq1)
$access=@(Invoke-SbAndroidAccessPathInventory $manifest);$inspections=[Collections.Generic.List[object]]::new();$eligible=0
foreach($record in $access){$partitionId=Protect-SbLevel1ReportValue $privacy 'partition' ([string]$record.PartitionGuid);$candidate=@($mvp.DetectedSystems|Where-Object{$_.CandidateKind-eq'PartitionCandidate'-and$_.PartitionId-ceq$partitionId}|Select-Object -First 1);if(-not$candidate.Count-or$candidate[0].FilesystemAccessibility-cne'AccessibleButNotReadByMvp'-or$candidate[0].Filesystem-notin@('FAT32','exFAT','NTFS')){continue};$eligible++;if($eligible-gt[int]$manifest.MaximumInspectableVolumes){throw 'ANDROID_VOLUME_RESOURCE_LIMIT'};$volumes=@($record.VolumeGuids|Sort-Object -Unique);if($volumes.Count-ne1){$inspections.Add([pscustomobject]@{Status='Denied';ReasonCode=if($volumes.Count){'ANDROID_EVIDENCE_VOLUME_AMBIGUOUS'}else{'ANDROID_EVIDENCE_VOLUME_PATH_UNAVAILABLE'};DiagnosticReasonCode=if($volumes.Count){'ACCESS_PATH_ALIAS_MISMATCH'}else{'ACCESS_PATH_UNAVAILABLE'};PartitionId=$partitionId;Evidence=@();NativeOpenOperations=0;BoundedReadOperations=0;BytesRead=0});continue};$inspections.Add((Invoke-SbWindowsAndroidEvidenceInspection -VolumeGuid ([guid]$volumes[0]) -PartitionId $partitionId -Filesystem ([string]$candidate[0].Filesystem) -EnableAndroidEvidence -GrantExplicitConsent))}
ConvertTo-SbMultiOsAndroidEvidenceReport -MvpReport $mvp -InspectionResults $inspections.ToArray()
