Set-StrictMode -Version Latest
function New-SbAndroidAccessibleManifest{
 [CmdletBinding()]param([Parameter(Mandatory)][string]$Level1ManifestDigest,[bool]$FeatureGateState=$false,[bool]$ExplicitConsent=$false,[bool]$NonElevated=$false,[ValidateSet('Passed','Failed','NotRun')][string]$PlatformCheck='NotRun')
 [pscustomobject][ordered]@{SchemaVersion='v9androidaccessibleexecution1';PackageRevision='Android-Initrd-Runtime-MVP.1';FeatureGateState=$FeatureGateState;ExplicitConsent=$ExplicitConsent;PlatformCheck=$PlatformCheck;NonElevated=$NonElevated;Level1ManifestDigest=$Level1ManifestDigest;DynamicDetectedSystems=$true;MaximumPartitionCandidates=4096;MaximumInspectableVolumes=256;MaximumFilesPerVolume=40;MaximumAggregateReadBytesPerVolume=262144;MaximumTextFileBytes=65536;MaximumInitrdCompressedBytes=33554432;MaximumInitrdDecompressedBytes=134217728;MaximumInitrdArchiveEntries=4096;MaximumInitrdEntryBytes=33554432;TimeoutMillisecondsPerVolume=10000;AllowedFilesystems=@('FAT32','exFAT','NTFS');ApprovedPathSetVersion='android-initrd-runtime-exact-paths-v1';OrdinaryVolumeReadAccess=$true;DirectoryEnumeration=$false;EfiAccess=$false;Mounts=$false;DriveLetterAssignment=$false;Elevation=$false;Writes=$false;BcdAccess=$false;NvramAccess=$false;SecureBootAccess=$false;BootOrderAccess=$false;PartitionWrites=$false;Network=$false;RefindAccess=$false}
}
function Test-SbAndroidAccessibleManifest{
 [CmdletBinding()]param([Parameter(Mandatory)][object]$Manifest);$codes=[Collections.Generic.List[string]]::new();$expected=@('SchemaVersion','PackageRevision','FeatureGateState','ExplicitConsent','PlatformCheck','NonElevated','Level1ManifestDigest','DynamicDetectedSystems','MaximumPartitionCandidates','MaximumInspectableVolumes','MaximumFilesPerVolume','MaximumAggregateReadBytesPerVolume','MaximumTextFileBytes','MaximumInitrdCompressedBytes','MaximumInitrdDecompressedBytes','MaximumInitrdArchiveEntries','MaximumInitrdEntryBytes','TimeoutMillisecondsPerVolume','AllowedFilesystems','ApprovedPathSetVersion','OrdinaryVolumeReadAccess','DirectoryEnumeration','EfiAccess','Mounts','DriveLetterAssignment','Elevation','Writes','BcdAccess','NvramAccess','SecureBootAccess','BootOrderAccess','PartitionWrites','Network','RefindAccess');if(@($Manifest.PSObject.Properties.Name|Where-Object{$_ -notin$expected}).Count-or@($expected|Where-Object{$_ -notin$Manifest.PSObject.Properties.Name}).Count){$codes.Add('ANDROID_MANIFEST_SHAPE_DENIED')};if($Manifest.SchemaVersion-cne'v9androidaccessibleexecution1'-or$Manifest.PackageRevision-cne'Android-Initrd-Runtime-MVP.1'){$codes.Add('ANDROID_MANIFEST_VERSION_DENIED')};if($Manifest.FeatureGateState-ne$true-or$Manifest.ExplicitConsent-ne$true-or$Manifest.PlatformCheck-cne'Passed'-or$Manifest.NonElevated-ne$true){$codes.Add('ANDROID_MANIFEST_GATE_DENIED')};if([string]$Manifest.Level1ManifestDigest-notmatch'^[0-9a-f]{64}$'-or$Manifest.DynamicDetectedSystems-ne$true-or[int]$Manifest.MaximumPartitionCandidates-ne4096-or[int]$Manifest.MaximumInspectableVolumes-ne256-or[int]$Manifest.MaximumFilesPerVolume-ne40-or[long]$Manifest.MaximumAggregateReadBytesPerVolume-ne262144-or[long]$Manifest.MaximumTextFileBytes-ne65536-or[long]$Manifest.MaximumInitrdCompressedBytes-ne33554432-or[long]$Manifest.MaximumInitrdDecompressedBytes-ne134217728-or[int]$Manifest.MaximumInitrdArchiveEntries-ne4096-or[int]$Manifest.MaximumInitrdEntryBytes-ne33554432-or[int]$Manifest.TimeoutMillisecondsPerVolume-ne10000-or$Manifest.ApprovedPathSetVersion-cne'android-initrd-runtime-exact-paths-v1'-or(@($Manifest.AllowedFilesystems)-join',')-cne'FAT32,exFAT,NTFS'){$codes.Add('ANDROID_MANIFEST_LIMIT_DENIED')};if($Manifest.OrdinaryVolumeReadAccess-ne$true){$codes.Add('ANDROID_MANIFEST_SCOPE_DENIED')};foreach($name in @('DirectoryEnumeration','EfiAccess','Mounts','DriveLetterAssignment','Elevation','Writes','BcdAccess','NvramAccess','SecureBootAccess','BootOrderAccess','PartitionWrites','Network','RefindAccess')){if($Manifest.$name-ne$false){$codes.Add('ANDROID_MANIFEST_FORBIDDEN_CAPABILITY')}};[pscustomobject]@{Allowed=($codes.Count-eq0);DiagnosticCodes=@($codes|Sort-Object -Unique)}
}
function Get-SbAndroidAccessibleManifestDigest{[CmdletBinding()]param([Parameter(Mandatory)][object]$Manifest);$a=[Security.Cryptography.SHA256]::Create();try{$h=$a.ComputeHash([Text.Encoding]::UTF8.GetBytes(($Manifest|ConvertTo-Json -Depth 20 -Compress)))}finally{$a.Dispose()};[BitConverter]::ToString($h).Replace('-','').ToLowerInvariant()}
Export-ModuleMember -Function New-SbAndroidAccessibleManifest,Test-SbAndroidAccessibleManifest,Get-SbAndroidAccessibleManifestDigest
