# SecretoBoot V9 FinalRelease.1 rEFInd theme. All paths are SecretoBoot-owned.
banner themes/SecretoBootV9/background.png
banner_scale fillscreen
icons_dir themes/SecretoBootV9/icons
selection_big themes/SecretoBootV9/selector.png
selection_small themes/SecretoBootV9/selector-small.png
big_icon_size 160
small_icon_size 80
hideui label,hints,badges,singleuser
