Set-StrictMode -Version Latest

function New-SbDiscoveryDiagnostics {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][AllowEmptyCollection()][object[]]$Systems,
        [Parameter(Mandatory)][AllowEmptyCollection()][object[]]$ExistingEvidence,
        [Parameter(Mandatory)][AllowEmptyCollection()][object[]]$AndroidInspections,
        [Parameter(Mandatory)][AllowEmptyCollection()][string[]]$ApprovedAndroidPaths,
        [Parameter(Mandatory)][int]$EspCandidateCount,
        [Parameter(Mandatory)][AllowEmptyCollection()][object[]]$EfiAccessRecords,
        [Parameter(Mandatory)][AllowEmptyCollection()][object[]]$EfiInspectionRecords,
        [Parameter(Mandatory)][AllowEmptyCollection()][object[]]$CanonicalEvidence,
        [AllowEmptyCollection()][object[]]$AndroidRelationships=@()
    )
    $diagnostics=[Collections.Generic.List[object]]::new()
    $usableEspPaths=@($EfiAccessRecords|Where-Object{@($_.VolumeGuids).Count-eq1}).Count
    $windowsLoader=@($CanonicalEvidence|Where-Object{([string]$_.RelativePath).ToLowerInvariant()-eq'efi/microsoft/boot/bootmgfw.efi'})
    $linuxLoaders=@($CanonicalEvidence|Where-Object{'linux-loader'-in@($_.Signals)})
    foreach($system in $Systems){
        $partition=[string]$system.PartitionId;$android=@($AndroidInspections|Where-Object{[string]$_.PartitionId-ceq$partition}|Select-Object -First 1);$ordinaryApplicable=$system.CandidateKind-ceq'PartitionCandidate'-and$system.Filesystem-in@('FAT32','exFAT','NTFS')
        $ordinaryAttempted=$android.Count-eq1;$existing=@($ExistingEvidence|Where-Object{[string]$_.PartitionId-ceq$partition});$existingPaths=@($existing|ForEach-Object{([string]$_.RelativePath).Replace('\','/')}|Sort-Object -Unique)
        $attemptedPaths=if($ordinaryAttempted){@($ApprovedAndroidPaths|Select-Object -First ([Math]::Min([int]$android[0].PathsAttempted,$ApprovedAndroidPaths.Count)))}else{@()}
        $absent=if($ordinaryAttempted-and$android[0].Status-ceq'Complete'){@($attemptedPaths|Where-Object{$_-notin$existingPaths})}else{@()};$inaccessible=if($ordinaryAttempted-and$android[0].Status-cne'Complete'){$attemptedPaths}else{@()}
        $espApplicable=$system.Family-in@('Windows','Linux');$espAttempted=$espApplicable-and$EfiInspectionRecords.Count-gt0;$volumePath=if($espApplicable){$usableEspPaths-gt0}elseif($ordinaryAttempted){$true}else{$false}
        $loaderResult='NOT_APPLICABLE';$configResult='NOT_APPLICABLE';$reason='NOT_APPLICABLE';$relationship=@($AndroidRelationships|Where-Object{[string]$_.BootPartitionId-ceq$partition-or[string]$_.SystemPartitionId-ceq$partition}|Select-Object -First 1);$androidChain=@($CanonicalEvidence|Where-Object{[string]$_.Kind-ceq'AndroidCanonicalBootChain'-and[string]$_.SourcePartitionToken-ceq$partition}|Select-Object -First 1)
        if($system.Family-ceq'Windows'){$loaderResult=if($windowsLoader.Count){'VALIDATED'}elseif($EspCandidateCount-eq0){'NOT_FOUND'}elseif($EfiAccessRecords.Count-eq0-or$usableEspPaths-eq0){'ACCESS_UNAVAILABLE'}elseif(@($EfiAccessRecords|Where-Object{@($_.VolumeGuids).Count-gt1}).Count){'AMBIGUOUS_ACCESS_PATH'}elseif(@($EfiInspectionRecords|Where-Object{$_.Status-ceq'Denied'-and$_.ReasonCode-match'ACCESS'}).Count){'ACCESS_DENIED'}else{'NOT_FOUND'};$reason=if($loaderResult-eq'VALIDATED'){'OWNERSHIP_UNPROVEN'}else{$loaderResult}}
        elseif($system.Family-ceq'Linux'){$loaderResult=if($linuxLoaders.Count){'VALIDATED'}elseif($EspCandidateCount-eq0){'NOT_FOUND'}elseif($EfiAccessRecords.Count-eq0-or$usableEspPaths-eq0){'ACCESS_UNAVAILABLE'}else{'NOT_FOUND'};$reason=if($loaderResult-eq'VALIDATED'){'RELATIONSHIP_UNPROVEN'}else{$loaderResult}}
        elseif($system.Family-ceq'Android'){$config=@($existing|Where-Object{[string]$_.Kind-ceq'BootConfig'});$allSignals=@($existing|ForEach-Object{$_.Signals}|Sort-Object -Unique);$configSignals=@($config|ForEach-Object{$_.Signals}|Sort-Object -Unique);$configResult=if(-not$ordinaryApplicable){'UNSUPPORTED_FILESYSTEM'}elseif(-not$ordinaryAttempted){'ACCESS_UNAVAILABLE'}elseif($android[0].Status-cne'Complete'){if([string]$android[0].ReasonCode-match'ACCESS'){'ACCESS_DENIED'}else{'RESOLVER_REJECTED'}}elseif(-not$config.Count){'CONFIG_MISSING'}elseif('android-boot-arguments'-notin$configSignals){'CONFIG_INVALID'}else{'ROOT_REFERENCE_MISSING'};$loaderResult=if(@(@('android-kernel','android-initrd','android-system-image')|Where-Object{$_-notin$allSignals}).Count){'LOADER_INVALID'}else{'VALIDATED'};$reason=$configResult;if($androidChain.Count){$loaderResult='VALIDATED';$configResult='VALIDATED';$reason='BOOT_TARGET_RESOLVED'}elseif($relationship.Count-and$relationship[0].RelationshipStatus-ceq'Proven'){$loaderResult='VALIDATED';$configResult='VALIDATED';$reason='BOOT_TARGET_RESOLVED'}elseif($relationship.Count){$reason=[string]@($relationship[0].ReasonCodes)[0]}}
        $itemSignals=@($existing|ForEach-Object{$_.Signals}|Sort-Object -Unique);$canonicalBliss='android-config-canonical'-in$itemSignals-and'bliss-os-identity'-in$itemSignals;$initrdInspected='initrd-archive-validated'-in$itemSignals;$runtimeStorage=if($androidChain.Count){'NeedsRuntimeDiscovery'}elseif($system.Family-ceq'Android'-and'android-system-image'-in$itemSignals){'UnprovenAtPreboot'}else{'NOT_APPLICABLE'}
        $diagnostics.Add([pscustomobject][ordered]@{SystemId=[string]$system.SystemId;PartitionId=if($partition){$partition}else{'NOT_APPLICABLE'};DiskId=if([string]$system.DiskId){[string]$system.DiskId}else{'NOT_APPLICABLE'};Filesystem=[string]$system.Filesystem;OrdinaryVolumeInspectionAttempted=$ordinaryAttempted;EspInspectionAttempted=$espAttempted;VolumeGuidAccessPathExisted=$volumePath;ApprovedPathsAttempted=$attemptedPaths;PathsExisted=$existingPaths;PathsAbsent=$absent;PathsInaccessible=$inaccessible;LoaderValidationResult=$loaderResult;ConfigValidationResult=$configResult;EvidenceIds=@($existing|ForEach-Object{$_.EvidenceId}|Sort-Object -Unique);CanonicalBlissConfig=if($canonicalBliss){'Valid'}else{'Invalid'};InitrdInspected=if($initrdInspected){'Yes'}else{'No'};RuntimeSystemDiscovery=if($androidChain.Count){'Proven'}else{'Unproven'};SrcBehavior=if($androidChain.Count){'Runtime'}elseif('initrd-src-handling'-in$itemSignals){'Static'}else{'Unknown'};SystemPartitionRequiredAtGrubStage=if($androidChain.Count){'No'}else{'Unknown'};RuntimeStorageCorrelationStatus=$runtimeStorage;AndroidRelationshipStatus=if($relationship.Count){[string]$relationship[0].RelationshipStatus}else{'NOT_APPLICABLE'};RootReferenceFound=if($relationship.Count){[bool]$relationship[0].RootReferenceFound}else{$false};ReferencedPartitionMatched=if($relationship.Count){[bool]$relationship[0].ReferencedPartitionMatched}else{$false};BootArgumentsValidated=if($relationship.Count){[bool]$relationship[0].BootArgumentsValidated}else{$false};CanonicalResolverRejectionReason=$reason;NeedsEvidenceReason=$reason})
    }
    return [pscustomobject][ordered]@{SchemaVersion='v9-discovery-diagnostics-1';EspCandidateDiscovered=($EspCandidateCount-gt0);EspCandidateCount=$EspCandidateCount;EfiAccessRecordCount=$EfiAccessRecords.Count;UsableEspVolumeGuidPathCount=$usableEspPaths;WindowsLoaderPathAttempted=($EfiInspectionRecords.Count-gt0);EfiVendorLoadersValidated=$CanonicalEvidence.Count;Items=$diagnostics.ToArray();OperationCounters=[pscustomobject]@{AdditionalFilesystemOperations=0;AdditionalEfiOperations=0;Writes=0;Mounts=0;DriveLetterAssignments=0}}
}

function Format-SbDiscoveryDiagnostics {
    [CmdletBinding()]param([Parameter(Mandatory)][object]$Diagnostics)
    $lines=[Collections.Generic.List[string]]::new();$lines.Add('SecretoBoot V9 Discovery Diagnostics');$lines.Add("ESP candidate discovered: $($Diagnostics.EspCandidateDiscovered)");$lines.Add("ESP candidates: $($Diagnostics.EspCandidateCount); access records: $($Diagnostics.EfiAccessRecordCount); usable volume-GUID paths: $($Diagnostics.UsableEspVolumeGuidPathCount)");$lines.Add("Windows loader path attempted: $($Diagnostics.WindowsLoaderPathAttempted); validated EFI loaders: $($Diagnostics.EfiVendorLoadersValidated)")
    foreach($item in $Diagnostics.Items){$lines.Add('');$lines.Add("System: $($item.SystemId)");$lines.Add("Partition: $($item.PartitionId); Disk: $($item.DiskId); Filesystem: $($item.Filesystem)");$lines.Add("Ordinary attempted: $($item.OrdinaryVolumeInspectionAttempted); ESP attempted: $($item.EspInspectionAttempted); volume-GUID path: $($item.VolumeGuidAccessPathExisted)");$lines.Add('Approved paths attempted: '+(@($item.ApprovedPathsAttempted)-join', '));$lines.Add('Paths with validated evidence: '+(@($item.PathsExisted)-join', '));$lines.Add('Paths without validated evidence: '+(@($item.PathsAbsent)-join', '));$lines.Add('Paths inaccessible: '+(@($item.PathsInaccessible)-join', '));$lines.Add("Canonical Bliss config: $($item.CanonicalBlissConfig); initrd inspected: $($item.InitrdInspected); runtime system discovery: $($item.RuntimeSystemDiscovery); SRC behavior: $($item.SrcBehavior); system partition required at GRUB stage: $($item.SystemPartitionRequiredAtGrubStage); runtime storage correlation: $($item.RuntimeStorageCorrelationStatus)");$lines.Add("Loader: $($item.LoaderValidationResult); Config: $($item.ConfigValidationResult); relationship: $($item.AndroidRelationshipStatus); root reference: $($item.RootReferenceFound); partition matched: $($item.ReferencedPartitionMatched); boot arguments: $($item.BootArgumentsValidated); Resolver: $($item.CanonicalResolverRejectionReason); NeedsEvidence: $($item.NeedsEvidenceReason)");$lines.Add('Evidence IDs: '+(@($item.EvidenceIds)-join', '))}
    return $lines.ToArray()-join"`r`n"
}

Export-ModuleMember -Function New-SbDiscoveryDiagnostics,Format-SbDiscoveryDiagnostics
