# SecretoBoot Enterprise v7.1 FINAL RELEASE
banner themes/SecretoBootV7_1/background.png
banner_scale fillscreen

icons_dir themes/SecretoBootV7_1/icons
selection_big themes/SecretoBootV7_1/selection_big.png
selection_small themes/SecretoBootV7_1/selection_small.png

big_icon_size 340
small_icon_size 96

hideui hints,badges
showtools reboot,firmware,shutdown
