# SecretoBoot Enterprise v7.1 FINAL RELEASE
$ErrorActionPreference = "Stop"
function Say($m){ Write-Host $m -ForegroundColor Cyan }
function OK($m){ Write-Host $m -ForegroundColor Green }
function Warn($m){ Write-Host $m -ForegroundColor Yellow }

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$rootDir = Split-Path -Parent $scriptDir
$themeSrc = Join-Path $rootDir "Theme\SecretoBootV7_1"

Say "[1/10] Searching for rEFInd..."
$refind = $null
Get-PSDrive -PSProvider FileSystem | ForEach-Object {
    $candidate = Join-Path ($_.Root) "EFI\refind"
    if ((Test-Path (Join-Path $candidate "refind.conf")) -and (Test-Path (Join-Path $candidate "refind_x64.efi"))) { $script:refind = $candidate }
}
if (-not $refind) {
    Say "rEFInd not visible. Mounting Windows EFI partition as S:..."
    cmd /c "mountvol S: /S" | Out-Null
    $candidate = "S:\EFI\refind"
    if ((Test-Path (Join-Path $candidate "refind.conf")) -and (Test-Path (Join-Path $candidate "refind_x64.efi"))) { $refind = $candidate }
}
if (-not $refind) { throw "Could not find rEFInd folder." }
OK "Found rEFInd: $refind"

$conf = Join-Path $refind "refind.conf"
$themes = Join-Path $refind "themes"
$themeDst = Join-Path $themes "SecretoBootV7_1"
$backupDir = Join-Path $refind "backups"
$refindIcons = Join-Path $refind "icons"
New-Item -ItemType Directory -Force -Path $themes,$backupDir,$refindIcons | Out-Null

Say "[2/10] Backup..."
$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
Copy-Item $conf (Join-Path $backupDir "refind.conf.before_SecretoBootV7_1_$stamp.bak") -Force
OK "Backup created."

Say "[3/10] Copying final theme..."
if (Test-Path $themeDst) { Remove-Item $themeDst -Recurse -Force }
Copy-Item $themeSrc $themeDst -Recurse -Force
OK "Theme copied."

Say "[4/10] Copying icons..."
$winSrc = Join-Path $themeSrc "icons\secreto_os_win.png"
$gtvSrc = Join-Path $themeSrc "icons\secreto_os_google_tv.png"
Copy-Item $winSrc (Join-Path $refindIcons "secreto_os_win.png") -Force
Copy-Item $gtvSrc (Join-Path $refindIcons "secreto_os_google_tv.png") -Force
OK "rEFInd ESP icons copied."

Say "[5/10] Finding Google TV BOOT partition..."
$bootDrive = $null
Get-Volume | ForEach-Object {
    if ($_.FileSystemLabel -eq "BOOT" -and $_.DriveLetter) {
        if (Test-Path "$($_.DriveLetter):\EFI\BOOT\BOOTx64.EFI") { $script:bootDrive = "$($_.DriveLetter):" }
    }
}
if ($bootDrive) {
    OK "Google TV BOOT found on $bootDrive"
    New-Item -ItemType Directory -Force -Path "$bootDrive\EFI\BOOT" | Out-Null
    Copy-Item $gtvSrc "$bootDrive\EFI\BOOT\secreto_os_google_tv.png" -Force
    Copy-Item $gtvSrc "$bootDrive\EFI\BOOT\os_google_tv.png" -Force
    OK "Google TV icon copied to BOOT partition."
} else {
    Warn "BOOT volume not visible. Google TV config will still use volume BOOT."
}

Say "[6/10] Writing manual refind.conf..."
$manual = @"
# SecretoBoot Enterprise v7.1 FINAL RELEASE
# Generated by Secretofnet
timeout 5
scanfor manual
default_selection "Windows 11"

dont_scan_dirs EFI/Boot,EFI/Microsoft,EFI/fydeos,EFI/tools
dont_scan_files BOOTX64.EFI,bootmgfw.efi,grubx64.efi,bootia32.efi

include themes/SecretoBootV7_1/theme.conf

menuentry "Windows 11" {
    icon /EFI/refind/icons/secreto_os_win.png
    loader /EFI/Microsoft/Boot/bootmgfw.efi
}

menuentry "Google TV OS" {
    volume BOOT
    icon /EFI/BOOT/secreto_os_google_tv.png
    loader /EFI/BOOT/BOOTx64.EFI
}
"@
Set-Content -Path $conf -Value $manual -Encoding ASCII
OK "refind.conf written."

Say "[7/10] Verification..."
$content = Get-Content $conf -Raw
if ($content -notmatch "scanfor manual") { throw "scanfor manual missing." }
if ($content -notmatch "SecretoBootV7_1") { throw "theme missing." }
if ($content -notmatch "/EFI/BOOT/secreto_os_google_tv.png") { throw "Google TV icon path missing." }
if (-not (Test-Path (Join-Path $themeDst "background.png"))) { throw "background missing." }
OK "Verification passed."

Say "[8/10] Active config:"
Select-String -Path $conf -Pattern "scanfor|include|menuentry|icon|loader|volume" | ForEach-Object { Write-Host $_.Line -ForegroundColor Gray }

Say "[9/10] Backup:"
Write-Host $backupDir -ForegroundColor Yellow

Say "[10/10] Done."
OK "SecretoBoot Enterprise v7.1 FINAL RELEASE installed successfully. Reboot to test."
